/*
Code for client (RISC-V board)
Aim:
    1. Run the instruction set generated by the server
    2. Sends the results back to the server (registers and memory states)

Things to consider:
    1. Smart filtering of immediates
    2. if a signal is triggered vs no signal triggered
    3. Handling infinite loops
    4. Unmapping Kernel-Provided Sections (vdso, vvar, etc.)
    5. run twice Detecting Naturally Non-Deterministic Instructions

*/

#include <fcntl.h>
#include <setjmp.h>
#include <signal.h>
#include <stdatomic.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <sys/time.h>
#include <ucontext.h>
#include <unistd.h>

#include "../main.h"
#include "client.h"

// extern variables
extern uint64_t xreg_init_data[];
extern uint64_t xreg_output_data[];
extern uint64_t freg_init_data[];
extern uint64_t freg_output_data[];

extern void signal_trampoline();  // from assembly
extern uint8_t* sandbox_ptr;

extern volatile atomic_uintptr_t g_fault_addr;
extern volatile sig_atomic_t g_faults_this_run;

// private definitions
#define MAX_FAULTS_PER_RUN 10
#define USER_VA_MAX (1ULL << 47)          // 0x8000_000000000
#define SANDBOX_BASE_ADDR 0x1000000000UL  // 64 GB

// private variables
const char* reg_names[] = {
    "x0 (zero)", "x1 (ra)",  "x2 (sp)",    "x3 (gp)",   "x4 (tp)",  "x5 (t0)",
    "x6 (t1)",   "x7 (t2)",  "x8 (s0/fp)", "x9 (s1)",   "x10 (a0)", "x11 (a1)",
    "x12 (a2)",  "x13 (a3)", "x14 (a4)",   "x15 (a5)",  "x16 (a6)", "x17 (a7)",
    "x18 (s2)",  "x19 (s3)", "x20 (s4)",   "x21 (s5)",  "x22 (s6)", "x23 (s7)",
    "x24 (s8)",  "x25 (s9)", "x26 (s10)",  "x27 (s11)", "x28 (t3)", "x29 (t4)",
    "x30 (t5)",  "x31 (t6)"};

sigjmp_buf jump_buffer;
ucontext_t saved_context;

// todo: consider sending this to server for comparison too
uint64_t fcsr_output_data;
char alt_stack[SIGSTKSZ];  // Signal alternate stack

size_t page_size = 4096;   // sysconf(_SC_PAGESIZE)
size_t sandbox_pages = 1;  // 4 KB sandbox
size_t guard_pages = 16;   // 64 KB guards (tunable)
size_t start_offset = 0x20;

struct sigaction old_sa_ill, old_sa_segv, old_sa_bus, old_sa_fpe, old_sa_trap,
    old_sa_alrm;
stack_t old_ss;

/**
 * @brief Signal handler for sandboxed execution faults.
 *
 * Handles SIGSEGV, SIGILL, SIGBUS, SIGFPE, SIGTRAP, and SIGALRM.
 *   - Saves general-purpose (x0-x31) and floating-point registers (f0-f31)
 *     plus fcsr from the sandbox context.
 *   - SIGSEGV:
 *       - Records the faulting address for lazy page mapping.
 *       - Aborts if PC escapes sandbox or fault occurs in restricted areas.
 *       - Retries execution if within fault threshold.
 *   - Other signals (SIGILL, SIGBUS, SIGFPE, SIGTRAP): abort via siglongjmp.
 *   - SIGALRM: triggered by timeout; aborts sandbox execution.
 *
 * Uses siglongjmp with different codes to signal the type of fault/recovery
 * action to the parent control loop.
 *
 * @param signo    Signal number received.
 * @param info     Pointer to siginfo_t with signal metadata.
 * @param context  Pointer to ucontext_t containing CPU state at fault.
 */
void signal_handler(int signo, siginfo_t* info, void* context) {
  ucontext_t* uc = (ucontext_t*)context;
  void* fault_addr = info->si_addr;
  uintptr_t pc = uc->uc_mcontext.__gregs[REG_PC];
  // === Save general-purpose registers (x0-x31) ===
  for (int i = 0; i < 32; i++) {
    xreg_output_data[i] = uc->uc_mcontext.__gregs[i];
  }

  // === Save floating-point registers if available ===
  union __riscv_mc_fp_state* fpstate = &uc->uc_mcontext.__fpregs;
  for (int i = 0; i < 32; i++) {
    freg_output_data[i] = fpstate->__d.__f[i];
  }
  fcsr_output_data = fpstate->__d.__fcsr;

  switch (signo) {
    case SIGILL:
    case SIGBUS:
    case SIGFPE:
    case SIGTRAP:
      log_append("Caught signal %d: %s\n", signo, strsignal(signo));
      siglongjmp(jump_buffer, 1);  // non-SIGSEGV fault
      break;

    case SIGSEGV:
      log_append("Caught SIGSEGV (Segmentation Fault)\n");
      // log_append("Faulting address: %p\n", fault_addr);

      if (pc == (uintptr_t)fault_addr) {
        // PC has escaped from sandbox. Abort
        log_append("[jump] PC escaped sandbox: 0x%lx\n", pc);
        siglongjmp(jump_buffer, 4);
      } else if ((uintptr_t)fault_addr >= (uintptr_t)sandbox_ptr &&
                     (uintptr_t)fault_addr <
                         ((uintptr_t)sandbox_ptr + page_size) ||
                 (uintptr_t)fault_addr >= USER_VA_MAX) {
        // SIGSEGV occured in sandbox page or kernel. Abort
        log_append(
            "SIGSEGV fault occured in restricted area. ERROR!! Returning\n");
        siglongjmp(jump_buffer, 4);
      } else if (g_faults_this_run >= MAX_FAULTS_PER_RUN) {
        log_append("threshold exceeded; proceeding anyway.\n");
        siglongjmp(jump_buffer, 3);  // threshold exceeded
      }

      atomic_store_explicit(&g_fault_addr, (uintptr_t)fault_addr,
                            memory_order_relaxed);
      g_faults_this_run++;
      // log_append("g_faults_this_run: %d\n", g_faults_this_run);
      siglongjmp(jump_buffer, 2);  // SIGSEV occured; retry

    case SIGALRM:
      log_append("Timeout: sandbox exceeded 100ms\n");
      siglongjmp(jump_buffer, 5);  // return with code 5 = timeout
      break;
    default:
      log_append("ERROR: SHOULD NOT RUN HERE!! %d\n", signo);
  }
}

/**
 * @brief Install signal handlers for sandboxed execution.
 *
 * Sets up an alternate stack and installs handlers for SIGILL, SIGSEGV,
 * SIGBUS, SIGFPE, SIGTRAP, and SIGALRM.
 *
 * All signals are directed to the sandbox's signal trampoline, which ultimately
 * calls the main signal handler.
 *
 * Uses SA_SIGINFO and SA_ONSTACK to safely handle faults on the alternate
 * stack.
 */
void setup_signal_handlers() {
  // save/replace sigaltstack
  sigaltstack(NULL, &old_ss);
  stack_t ss = {
      .ss_sp = alt_stack, .ss_size = sizeof(alt_stack), .ss_flags = 0};
  sigaltstack(&ss, NULL);

  struct sigaction sa;
  memset(&sa, 0, sizeof(sa));
  sa.sa_sigaction = (void*)signal_trampoline;
  sa.sa_flags = SA_SIGINFO | SA_ONSTACK;
  sigemptyset(&sa.sa_mask);

  sigaction(SIGILL, &sa, NULL);
  sigaction(SIGSEGV, &sa, NULL);
  sigaction(SIGBUS, &sa, NULL);
  sigaction(SIGFPE, &sa, NULL);
  sigaction(SIGTRAP, &sa, NULL);
  sigaction(SIGALRM, &sa, NULL);
}

/**
 * @brief Restore the original signal handlers and alternate stack.
 *
 * Reverts all signals previously overridden by setup_signal_handlers()
 * to their original handlers.
 * Also restores the previous alternate stack to ensure host state integrity.
 */
void restore_signal_handlers() {
  sigaction(SIGILL, &old_sa_ill, NULL);
  sigaction(SIGSEGV, &old_sa_segv, NULL);
  sigaction(SIGBUS, &old_sa_bus, NULL);
  sigaction(SIGFPE, &old_sa_fpe, NULL);
  sigaction(SIGTRAP, &old_sa_trap, NULL);
  sigaction(SIGALRM, &old_sa_alrm, NULL);

  // restore altstack
  if (sigaltstack(&old_ss, NULL) != 0) perror("sigaltstack restore");
}

/**
 * @brief Allocate a protected, executable sandbox region.
 *
 * Reserves a contiguous range of pages at SANDBOX_BASE_ADDR using PROT_NONE.
 * The region layout is:
 *   [guard pages][sandbox pages][guard pages]
 */
uint8_t* allocate_executable_buffer() {
  size_t total_pages = sandbox_pages + 2 * guard_pages;
  size_t total_size = total_pages * page_size;

  void* buf = mmap((void*)SANDBOX_BASE_ADDR, total_size, PROT_NONE,
                   MAP_ANONYMOUS | MAP_PRIVATE | MAP_FIXED_NOREPLACE, -1, 0);

  if (buf == MAP_FAILED) {
    perror("mmap sandbox buffer");
    exit(1);
  }

  uint8_t* sandbox = buf + guard_pages * page_size;
  return sandbox;
}

/**
 * @brief Free the sandbox allocation created by allocate_executable_buffer().
 * Called when the client closes its TCP connection with the server.
 */
void free_executable_buffer(uint8_t* sandbox) {
  size_t total_pages = sandbox_pages + 2 * guard_pages;
  size_t total_size = total_pages * page_size;

  // compute back the original base (buf)
  void* buf = sandbox - guard_pages * page_size;

  if ((uintptr_t)buf % page_size != 0) {
    fprintf(stderr, "munmap addr not page-aligned: %p\n", buf);
  }
  if (total_size % page_size != 0) {
    fprintf(stderr, "munmap len not page-size aligned: %zu\n", total_size);
  }

  if (munmap(buf, total_size) != 0) {
    perror("munmap failed");
  }
}

/**
 * @brief Reset sandbox memory protections to PROT_NONE.
 *
 * Called before each execution run to ensure the sandbox region begins fully
 * inaccessible. Also clears values in sandbox region.
 */
void prepare_sandbox(uint8_t* sandbox_ptr) {
  if (mprotect(sandbox_ptr, page_size * sandbox_pages, PROT_NONE) != 0) {
    perror("mprotect NONE");
    exit(1);
  }
}

/**
 * @brief Inject fuzzed instructions into the sandbox and make them executable.
 *
 * 1. Writes two leading and  * two trailing ebreak instructions as safety
 * padding
 * 2. Copies the fuzzed instruction sequence
 * 3. Issues `fence.i` to flush the instruction cache
 * 4. Transitions the sandbox region to RX permissions so the injected code can
 * be executed safely.
 */
void inject_instructions(uint8_t* sandbox_ptr, const uint32_t* instrs,
                         size_t num_instrs) {
  // enable write access
  if (mprotect(sandbox_ptr, sandbox_pages * page_size,
               PROT_READ | PROT_WRITE) != 0) {
    perror("mprotect");
    exit(1);
  }

  // fill 2 ebreaks before the sandboxed instructions
  for (size_t i = 0; i < 2 * sizeof(uint32_t); i += 4)
    *(uint32_t*)(sandbox_ptr + start_offset - 2 * sizeof(uint32_t) + i) =
        0x00100073;

  // fill 2 ebreaks after the sandboxed instructions
  for (size_t i = 0; i < 2 * sizeof(uint32_t); i += 4)
    *(uint32_t*)(sandbox_ptr + start_offset + num_instrs * sizeof(uint32_t) +
                 i) = 0x00100073;

  // copy fuzzed instructions
  memcpy(sandbox_ptr + start_offset, instrs, num_instrs * sizeof(uint32_t));

  // flush instruction cache, preventing inconsistent results
  asm volatile("fence.i" ::: "memory");

  // make page executable
  if (mprotect(sandbox_ptr, sandbox_pages * page_size, PROT_READ | PROT_EXEC) !=
      0) {
    perror("mprotect RX");
    exit(1);
  }
}

// Unmaps VDSO and VVAR pages from this process.
void unmap_vdso_vvar() {
  FILE* maps = fopen("/proc/self/maps", "r");
  if (!maps) {
    perror("fopen /proc/self/maps");
    exit(EXIT_FAILURE);
  }

  char line[256];
  while (fgets(line, sizeof(line), maps)) {
    if (strstr(line, "[vdso]") || strstr(line, "[vdso_data]") ||
        strstr(line, "[vvar]")) {
      unsigned long start, end;
      if (sscanf(line, "%lx-%lx", &start, &end) == 2) {
        // printf("Unmapping %lx - %lx\n", start, end);
        if (munmap((void*)start, end - start) != 0) {
          perror("Warning: unmapping has failed!!");
        }
      }
    }
  }
  fclose(maps);
}

/**
 * @brief Print architectural changes in general-purpose registers (x1–x31).
 *
 * x0 is skipped (always 0), and x9 is skipped because it stores the
 * trampoline return address for sandbox escape.
 */
void print_xreg_changes(void) {
  // skip x0 since it is hardwired to 0
  for (int i = 1; i < 32; i++) {
    if (i == 9)  // skip x9 as it is used for storing the return jump pointer
                 // out of sandbox
      continue;

    if (xreg_init_data[i] != xreg_output_data[i]) {
      log_append("%-4s:-> 0x%016lx\n", reg_names[i], xreg_output_data[i]);
    }
  }
}

// lookup table: true means mask upper 32 bits for that freg
static const bool special_mask[32] = {
    [2] = true,  [3] = true,  [4] = true,  [5] = true,  [6] = true,
    [7] = true,  [8] = true,  [10] = true, [13] = true, [14] = true,
    [15] = true, [16] = true, [17] = true, [20] = true, [22] = true,
    [25] = true, [29] = true, [30] = true,
};

/**
 * @brief Print floating-point register changes with architecture-specific
 * masks.
 *
 * Some floating‑point registers expose only their lower 32 bits. For these,
 * the upper 32 bits are masked off before comparison, ensuring differences are
 * meaningful. Any register whose (possibly masked) value changed is logged.
 */
void print_freg_changes(void) {
  for (int i = 0; i < 32; i++) {
    uint64_t before = freg_init_data[i];
    uint64_t after = freg_output_data[i];

    // Hard-coded list of registers that only show lower 32 bits
    if (special_mask[i]) {
      before = 0xffffffff00000000ULL | (before & 0xffffffffULL);
      after = 0xffffffff00000000ULL | (after & 0xffffffffULL);
    }
    // compare is the same (after possible masking)
    if (before != after) {
      log_append("f%-3d: 0x%016lx -> 0x%016lx\n", i, before, after);
    }
  }
}
