import re

# Example input
input_lines = """
{"th.addsl", 0, INSN_CLASS_XTHEADBA, "d,s,t,Xtu2@25", MATCH_TH_ADDSL,
    MASK_TH_ADDSL, match_opcode, 0},
{"th.srri", 0, INSN_CLASS_XTHEADBB, "d,s,Xtu6@20", MATCH_TH_SRRI,
    MASK_TH_SRRI, match_opcode, 0},
{"th.srriw", 64, INSN_CLASS_XTHEADBB, "d,s,Xtu5@20", MATCH_TH_SRRIW,
    MASK_TH_SRRIW, match_opcode, 0},
{"th.ext", 0, INSN_CLASS_XTHEADBB, "d,s,Xtu6@26,Xtu6@20", MATCH_TH_EXT,
    MASK_TH_EXT, match_opcode, 0},
{"th.extu", 0, INSN_CLASS_XTHEADBB, "d,s,Xtu6@26,Xtu6@20", MATCH_TH_EXTU,
    MASK_TH_EXTU, match_opcode, 0},
{"th.ff0", 0, INSN_CLASS_XTHEADBB, "d,s", MATCH_TH_FF0, MASK_TH_FF0,
    match_opcode, 0},
{"th.ff1", 0, INSN_CLASS_XTHEADBB, "d,s", MATCH_TH_FF1, MASK_TH_FF1,
    match_opcode, 0},
{"th.rev", 0, INSN_CLASS_XTHEADBB, "d,s", MATCH_TH_REV, MASK_TH_REV,
    match_opcode, 0},
{"th.revw", 64, INSN_CLASS_XTHEADBB, "d,s", MATCH_TH_REVW, MASK_TH_REVW,
    match_opcode, 0},
{"th.tstnbz", 0, INSN_CLASS_XTHEADBB, "d,s", MATCH_TH_TSTNBZ,
    MASK_TH_TSTNBZ, match_opcode, 0},
{"th.tst", 0, INSN_CLASS_XTHEADBS, "d,s,Xtu6@20", MATCH_TH_TST, MASK_TH_TST,
    match_opcode, 0},
{"th.dcache.call", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_DCACHE_CALL,
    MASK_TH_DCACHE_CALL, match_opcode, 0},
{"th.dcache.ciall", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_DCACHE_CIALL,
    MASK_TH_DCACHE_CIALL, match_opcode, 0},
{"th.dcache.iall", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_DCACHE_IALL,
    MASK_TH_DCACHE_IALL, match_opcode, 0},
{"th.dcache.cpa", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CPA,
    MASK_TH_DCACHE_CPA, match_opcode, 0},
{"th.dcache.cipa", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CIPA,
    MASK_TH_DCACHE_CIPA, match_opcode, 0},
{"th.dcache.ipa", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_IPA,
    MASK_TH_DCACHE_IPA, match_opcode, 0},
{"th.dcache.cva", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CVA,
    MASK_TH_DCACHE_CVA, match_opcode, 0},
{"th.dcache.civa", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CIVA,
    MASK_TH_DCACHE_CIVA, match_opcode, 0},
{"th.dcache.iva", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_IVA,
    MASK_TH_DCACHE_IVA, match_opcode, 0},
{"th.dcache.csw", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CSW,
    MASK_TH_DCACHE_CSW, match_opcode, 0},
{"th.dcache.cisw", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CISW,
    MASK_TH_DCACHE_CISW, match_opcode, 0},
{"th.dcache.isw", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_ISW,
    MASK_TH_DCACHE_ISW, match_opcode, 0},
{"th.dcache.cpal1", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CPAL1,
    MASK_TH_DCACHE_CPAL1, match_opcode, 0},
{"th.dcache.cval1", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_DCACHE_CVAL1,
    MASK_TH_DCACHE_CVAL1, match_opcode, 0},
{"th.icache.iall", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_ICACHE_IALL,
    MASK_TH_ICACHE_IALL, match_opcode, 0},
{"th.icache.ialls", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_ICACHE_IALLS,
    MASK_TH_ICACHE_IALLS, match_opcode, 0},
{"th.icache.ipa", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_ICACHE_IPA,
    MASK_TH_ICACHE_IPA, match_opcode, 0},
{"th.icache.iva", 0, INSN_CLASS_XTHEADCMO, "s", MATCH_TH_ICACHE_IVA,
    MASK_TH_ICACHE_IVA, match_opcode, 0},
{"th.l2cache.call", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_L2CACHE_CALL,
    MASK_TH_L2CACHE_CALL, match_opcode, 0},
{"th.l2cache.ciall", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_L2CACHE_CIALL,
    MASK_TH_L2CACHE_CIALL, match_opcode, 0},
{"th.l2cache.iall", 0, INSN_CLASS_XTHEADCMO, "", MATCH_TH_L2CACHE_IALL,
    MASK_TH_L2CACHE_IALL, match_opcode, 0},
{"th.mveqz", 0, INSN_CLASS_XTHEADCONDMOV, "d,s,t", MATCH_TH_MVEQZ,
    MASK_TH_MVEQZ, match_opcode, 0},
{"th.mvnez", 0, INSN_CLASS_XTHEADCONDMOV, "d,s,t", MATCH_TH_MVNEZ,
    MASK_TH_MVNEZ, match_opcode, 0},
{"th.flrd", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FLRD,
    MASK_TH_FLRD, match_opcode, 0},
{"th.flrw", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FLRW,
    MASK_TH_FLRW, match_opcode, 0},
{"th.flurd", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FLURD,
    MASK_TH_FLURD, match_opcode, 0},
{"th.flurw", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FLURW,
    MASK_TH_FLURW, match_opcode, 0},
{"th.fsrd", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FSRD,
    MASK_TH_FSRD, match_opcode, 0},
{"th.fsrw", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FSRW,
    MASK_TH_FSRW, match_opcode, 0},
{"th.fsurd", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FSURD,
    MASK_TH_FSURD, match_opcode, 0},
{"th.fsurw", 0, INSN_CLASS_XTHEADFMEMIDX, "D,s,t,Xtu2@25", MATCH_TH_FSURW,
    MASK_TH_FSURW, match_opcode, 0},
{"th.fmv.hw.x", 32, INSN_CLASS_XTHEADFMV, "D,s", MATCH_TH_FMV_HW_X,
    MASK_TH_FMV_HW_X, match_opcode, 0},
{"th.fmv.x.hw", 32, INSN_CLASS_XTHEADFMV, "d,S", MATCH_TH_FMV_X_HW,
    MASK_TH_FMV_X_HW, match_opcode, 0},
{"th.ipop", 0, INSN_CLASS_XTHEADINT, "", MATCH_TH_IPOP, MASK_TH_IPOP,
    match_opcode, 0},
{"th.ipush", 0, INSN_CLASS_XTHEADINT, "", MATCH_TH_IPUSH, MASK_TH_IPUSH,
    match_opcode, 0},
{"th.ldia", 64, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LDIA, MASK_TH_LDIA, match_th_load_inc, 0},
{"th.ldib", 64, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LDIB, MASK_TH_LDIB, match_th_load_inc, 0},
{"th.lwia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LWIA, MASK_TH_LWIA, match_th_load_inc, 0},
{"th.lwib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LWIB, MASK_TH_LWIB, match_th_load_inc, 0},
{"th.lwuia", 64, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LWUIA, MASK_TH_LWUIA, match_th_load_inc, 0},
{"th.lwuib", 64, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LWUIB, MASK_TH_LWUIB, match_th_load_inc, 0},
{"th.lhia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LHIA, MASK_TH_LHIA, match_th_load_inc, 0},
{"th.lhib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LHIB, MASK_TH_LHIB, match_th_load_inc, 0},
{"th.lhuia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LHUIA, MASK_TH_LHUIA, match_th_load_inc, 0},
{"th.lhuib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LHUIB, MASK_TH_LHUIB, match_th_load_inc, 0},
{"th.lbia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LBIA, MASK_TH_LBIA, match_th_load_inc, 0},
{"th.lbib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LBIB, MASK_TH_LBIB, match_th_load_inc, 0},
{"th.lbuia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LBUIA, MASK_TH_LBUIA, match_th_load_inc, 0},
{"th.lbuib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_LBUIB, MASK_TH_LBUIB, match_th_load_inc, 0},
{"th.sdia", 64, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SDIA, MASK_TH_SDIA, match_opcode, 0},
{"th.sdib", 64, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SDIB, MASK_TH_SDIB, match_opcode, 0},
{"th.swia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SWIA, MASK_TH_SWIA, match_opcode, 0},
{"th.swib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SWIB, MASK_TH_SWIB, match_opcode, 0},
{"th.shia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SHIA, MASK_TH_SHIA, match_opcode, 0},
{"th.shib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SHIB, MASK_TH_SHIB, match_opcode, 0},
{"th.sbia", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SBIA, MASK_TH_SBIA, match_opcode, 0},
{"th.sbib", 0, INSN_CLASS_XTHEADMEMIDX, "d,(s),Xts5@20,Xtu2@25",
    MATCH_TH_SBIB, MASK_TH_SBIB, match_opcode, 0},
{"th.lrd", 64, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LRD,
    MASK_TH_LRD, match_opcode, 0},
{"th.lrw", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LRW,
    MASK_TH_LRW, match_opcode, 0},
{"th.lrwu", 64, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LRWU,
    MASK_TH_LRWU, match_opcode, 0},
{"th.lrh", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LRH,
    MASK_TH_LRH, match_opcode, 0},
{"th.lrhu", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LRHU,
    MASK_TH_LRHU, match_opcode, 0},
{"th.lrb", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LRB,
    MASK_TH_LRB, match_opcode, 0},
{"th.lrbu", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LRBU,
    MASK_TH_LRBU, match_opcode, 0},
{"th.srd", 64, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SRD,
    MASK_TH_SRD, match_opcode, 0},
{"th.srw", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SRW,
    MASK_TH_SRW, match_opcode, 0},
{"th.srh", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SRH,
    MASK_TH_SRH, match_opcode, 0},
{"th.srb", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SRB,
    MASK_TH_SRB, match_opcode, 0},
{"th.lurd", 64, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LURD,
    MASK_TH_LURD, match_opcode, 0},
{"th.lurw", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LURW,
    MASK_TH_LURW, match_opcode, 0},
{"th.lurwu", 64, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LURWU,
    MASK_TH_LURWU, match_opcode, 0},
{"th.lurh", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LURH,
    MASK_TH_LURH, match_opcode, 0},
{"th.lurhu", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LURHU,
    MASK_TH_LURHU, match_opcode, 0},
{"th.lurb", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LURB,
    MASK_TH_LURB, match_opcode, 0},
{"th.lurbu", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_LURBU,
    MASK_TH_LURBU, match_opcode, 0},
{"th.surd", 64, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SURD,
    MASK_TH_SURD, match_opcode, 0},
{"th.surw", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SURW,
    MASK_TH_SURW, match_opcode, 0},
{"th.surh", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SURH,
    MASK_TH_SURH, match_opcode, 0},
{"th.surb", 0, INSN_CLASS_XTHEADMEMIDX, "d,s,t,Xtu2@25", MATCH_TH_SURB,
    MASK_TH_SURB, match_opcode, 0},
{"th.ldd", 64, INSN_CLASS_XTHEADMEMPAIR, "d,t,(s),Xtu2@25,Xtl4",
    MATCH_TH_LDD, MASK_TH_LDD, match_th_load_pair, 0},
{"th.lwd", 0, INSN_CLASS_XTHEADMEMPAIR, "d,t,(s),Xtu2@25,Xtl3",
    MATCH_TH_LWD, MASK_TH_LWD, match_th_load_pair, 0},
{"th.lwud", 0, INSN_CLASS_XTHEADMEMPAIR, "d,t,(s),Xtu2@25,Xtl3",
    MATCH_TH_LWUD, MASK_TH_LWUD, match_th_load_pair, 0},
{"th.sdd", 64, INSN_CLASS_XTHEADMEMPAIR, "d,t,(s),Xtu2@25,Xtl4",
    MATCH_TH_SDD, MASK_TH_SDD, match_opcode, 0},
{"th.swd", 0, INSN_CLASS_XTHEADMEMPAIR, "d,t,(s),Xtu2@25,Xtl3",
    MATCH_TH_SWD, MASK_TH_SWD, match_opcode, 0},
{"th.mula", 0, INSN_CLASS_XTHEADMAC, "d,s,t", MATCH_TH_MULA, MASK_TH_MULA,
    match_opcode, 0},
{"th.mulah", 0, INSN_CLASS_XTHEADMAC, "d,s,t", MATCH_TH_MULAH,
    MASK_TH_MULAH, match_opcode, 0},
{"th.mulaw", 64, INSN_CLASS_XTHEADMAC, "d,s,t", MATCH_TH_MULAW,
    MASK_TH_MULAW, match_opcode, 0},
{"th.muls", 0, INSN_CLASS_XTHEADMAC, "d,s,t", MATCH_TH_MULS, MASK_TH_MULS,
    match_opcode, 0},
{"th.mulsh", 0, INSN_CLASS_XTHEADMAC, "d,s,t", MATCH_TH_MULSH,
    MASK_TH_MULSH, match_opcode, 0},
{"th.mulsw", 64, INSN_CLASS_XTHEADMAC, "d,s,t", MATCH_TH_MULSW,
    MASK_TH_MULSW, match_opcode, 0},
{"th.sfence.vmas", 0, INSN_CLASS_XTHEADSYNC, "s,t", MATCH_TH_SFENCE_VMAS,
    MASK_TH_SFENCE_VMAS, match_opcode, 0},
{"th.sync", 0, INSN_CLASS_XTHEADSYNC, "", MATCH_TH_SYNC, MASK_TH_SYNC,
    match_opcode, 0},
{"th.sync.i", 0, INSN_CLASS_XTHEADSYNC, "", MATCH_TH_SYNC_I, MASK_TH_SYNC_I,
    match_opcode, 0},
{"th.sync.is", 0, INSN_CLASS_XTHEADSYNC, "", MATCH_TH_SYNC_IS,
    MASK_TH_SYNC_IS, match_opcode, 0},
{"th.sync.s", 0, INSN_CLASS_XTHEADSYNC, "", MATCH_TH_SYNC_S, MASK_TH_SYNC_S,
    match_opcode, 0},

/* Vendor-specific (T-Head) XTheadVector instructions.  */
{"th.vsetvl", 0, INSN_CLASS_XTHEADVECTOR, "d,s,t", MATCH_VSETVL,
    MASK_VSETVL, match_opcode, 0},
{"th.vsetvli", 0, INSN_CLASS_XTHEADVECTOR, "d,s,XtVc", MATCH_VSETVLI,
    MASK_VSETVLI, match_opcode, 0},
{"th.vlb.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLBV,
    MASK_TH_VLBV, match_opcode, INSN_DREF},
{"th.vlh.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLHV,
    MASK_TH_VLHV, match_opcode, INSN_DREF},
{"th.vlw.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLWV,
    MASK_TH_VLWV, match_opcode, INSN_DREF},
{"th.vlbu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE8V,
    MASK_VLE8V, match_opcode, INSN_DREF},
{"th.vlhu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE16V,
    MASK_VLE16V, match_opcode, INSN_DREF},
{"th.vlwu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE32V,
    MASK_VLE32V, match_opcode, INSN_DREF},
{"th.vle.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE64V,
    MASK_VLE64V, match_opcode, INSN_DREF},
{"th.vsb.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSE8V,
    MASK_VSE8V, match_opcode, INSN_DREF},
{"th.vsh.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSE16V,
    MASK_VSE16V, match_opcode, INSN_DREF},
{"th.vsw.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSE32V,
    MASK_VSE32V, match_opcode, INSN_DREF},
{"th.vse.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSE64V,
    MASK_VSE64V, match_opcode, INSN_DREF},
{"th.vlsb.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_TH_VLSBV,
    MASK_TH_VLSBV, match_opcode, INSN_DREF},
{"th.vlsh.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_TH_VLSHV,
    MASK_TH_VLSHV, match_opcode, INSN_DREF},
{"th.vlsw.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_TH_VLSWV,
    MASK_TH_VLSWV, match_opcode, INSN_DREF},
{"th.vlsbu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VLSE8V,
    MASK_VLSE8V, match_opcode, INSN_DREF},
{"th.vlshu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VLSE16V,
    MASK_VLSE16V, match_opcode, INSN_DREF},
{"th.vlswu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VLSE32V,
    MASK_VLSE32V, match_opcode, INSN_DREF},
{"th.vlse.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VLSE64V,
    MASK_VLSE64V, match_opcode, INSN_DREF},
{"th.vssb.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VSSE8V,
    MASK_VSSE8V, match_opcode, INSN_DREF},
{"th.vssh.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VSSE16V,
    MASK_VSSE16V, match_opcode, INSN_DREF},
{"th.vssw.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VSSE32V,
    MASK_VSSE32V, match_opcode, INSN_DREF},
{"th.vsse.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm", MATCH_VSSE64V,
    MASK_VSSE64V, match_opcode, INSN_DREF},
{"th.vlxb.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_TH_VLXBV,
    MASK_TH_VLXBV, match_opcode, INSN_DREF},
{"th.vlxh.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_TH_VLXHV,
    MASK_TH_VLXHV, match_opcode, INSN_DREF},
{"th.vlxw.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_TH_VLXWV,
    MASK_TH_VLXWV, match_opcode, INSN_DREF},
{"th.vlxbu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VLOXEI8V,
    MASK_VLOXEI8V, match_opcode, INSN_DREF},
{"th.vlxhu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VLOXEI16V,
    MASK_VLOXEI16V, match_opcode, INSN_DREF},
{"th.vlxwu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VLOXEI32V,
    MASK_VLOXEI32V, match_opcode, INSN_DREF},
{"th.vlxe.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VLOXEI64V,
    MASK_VLOXEI64V, match_opcode, INSN_DREF},
{"th.vsxb.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VSOXEI8V,
    MASK_VSOXEI8V, match_opcode, INSN_DREF},
{"th.vsxh.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VSOXEI16V,
    MASK_VSOXEI16V, match_opcode, INSN_DREF},
{"th.vsxw.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VSOXEI32V,
    MASK_VSOXEI32V, match_opcode, INSN_DREF},
{"th.vsxe.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_VSOXEI64V,
    MASK_VSOXEI64V, match_opcode, INSN_DREF},
{"th.vsuxb.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_TH_VSUXBV,
    MASK_TH_VSUXBV, match_opcode, INSN_DREF},
{"th.vsuxh.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_TH_VSUXHV,
    MASK_TH_VSUXHV, match_opcode, INSN_DREF},
{"th.vsuxw.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_TH_VSUXWV,
    MASK_TH_VSUXWV, match_opcode, INSN_DREF},
{"th.vsuxe.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm", MATCH_TH_VSUXEV,
    MASK_TH_VSUXEV, match_opcode, INSN_DREF},
{"th.vlbff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLBFFV,
    MASK_TH_VLBFFV, match_opcode, INSN_DREF},
{"th.vlhff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLHFFV,
    MASK_TH_VLHFFV, match_opcode, INSN_DREF},
{"th.vlwff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLWFFV,
    MASK_TH_VLWFFV, match_opcode, INSN_DREF},
{"th.vlbuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE8FFV,
    MASK_VLE8FFV, match_opcode, INSN_DREF},
{"th.vlhuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE16FFV,
    MASK_VLE16FFV, match_opcode, INSN_DREF},
{"th.vlwuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE32FFV,
    MASK_VLE32FFV, match_opcode, INSN_DREF},
{"th.vleff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLE64FFV,
    MASK_VLE64FFV, match_opcode, INSN_DREF},
{"th.vlseg2b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG2BV,
    MASK_TH_VLSEG2BV, match_opcode, INSN_DREF},
{"th.vlseg2h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG2HV,
    MASK_TH_VLSEG2HV, match_opcode, INSN_DREF},
{"th.vlseg2w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG2WV,
    MASK_TH_VLSEG2WV, match_opcode, INSN_DREF},
{"th.vlseg2bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG2E8V,
    MASK_VLSEG2E8V, match_opcode, INSN_DREF},
{"th.vlseg2hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG2E16V,
    MASK_VLSEG2E16V, match_opcode, INSN_DREF},
{"th.vlseg2wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG2E32V,
    MASK_VLSEG2E32V, match_opcode, INSN_DREF},
{"th.vlseg2e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG2E64V,
    MASK_VLSEG2E64V, match_opcode, INSN_DREF},
{"th.vsseg2b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG2E8V,
    MASK_VSSEG2E8V, match_opcode, INSN_DREF},
{"th.vsseg2h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG2E16V,
    MASK_VSSEG2E16V, match_opcode, INSN_DREF},
{"th.vsseg2w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG2E32V,
    MASK_VSSEG2E32V, match_opcode, INSN_DREF},
{"th.vsseg2e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG2E64V,
    MASK_VSSEG2E64V, match_opcode, INSN_DREF},
{"th.vlseg3b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG3BV,
    MASK_TH_VLSEG3BV, match_opcode, INSN_DREF},
{"th.vlseg3h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG3HV,
    MASK_TH_VLSEG3HV, match_opcode, INSN_DREF},
{"th.vlseg3w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG3WV,
    MASK_TH_VLSEG3WV, match_opcode, INSN_DREF},
{"th.vlseg3bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG3E8V,
    MASK_VLSEG3E8V, match_opcode, INSN_DREF},
{"th.vlseg3hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG3E16V,
    MASK_VLSEG3E16V, match_opcode, INSN_DREF},
{"th.vlseg3wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG3E32V,
    MASK_VLSEG3E32V, match_opcode, INSN_DREF},
{"th.vlseg3e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG3E64V,
    MASK_VLSEG3E64V, match_opcode, INSN_DREF},
{"th.vsseg3b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG3E8V,
    MASK_VSSEG3E8V, match_opcode, INSN_DREF},
{"th.vsseg3h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG3E16V,
    MASK_VSSEG3E16V, match_opcode, INSN_DREF},
{"th.vsseg3w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG3E32V,
    MASK_VSSEG3E32V, match_opcode, INSN_DREF},
{"th.vsseg3e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG3E64V,
    MASK_VSSEG3E64V, match_opcode, INSN_DREF},
{"th.vlseg4b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG4BV,
    MASK_TH_VLSEG4BV, match_opcode, INSN_DREF},
{"th.vlseg4h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG4HV,
    MASK_TH_VLSEG4HV, match_opcode, INSN_DREF},
{"th.vlseg4w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG4WV,
    MASK_TH_VLSEG4WV, match_opcode, INSN_DREF},
{"th.vlseg4bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG4E8V,
    MASK_VLSEG4E8V, match_opcode, INSN_DREF},
{"th.vlseg4hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG4E16V,
    MASK_VLSEG4E16V, match_opcode, INSN_DREF},
{"th.vlseg4wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG4E32V,
    MASK_VLSEG4E32V, match_opcode, INSN_DREF},
{"th.vlseg4e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG4E64V,
    MASK_VLSEG4E64V, match_opcode, INSN_DREF},
{"th.vsseg4b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG4E8V,
    MASK_VSSEG4E8V, match_opcode, INSN_DREF},
{"th.vsseg4h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG4E16V,
    MASK_VSSEG4E16V, match_opcode, INSN_DREF},
{"th.vsseg4w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG4E32V,
    MASK_VSSEG4E32V, match_opcode, INSN_DREF},
{"th.vsseg4e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG4E64V,
    MASK_VSSEG4E64V, match_opcode, INSN_DREF},
{"th.vlseg5b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG5BV,
    MASK_TH_VLSEG5BV, match_opcode, INSN_DREF},
{"th.vlseg5h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG5HV,
    MASK_TH_VLSEG5HV, match_opcode, INSN_DREF},
{"th.vlseg5w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG5WV,
    MASK_TH_VLSEG5WV, match_opcode, INSN_DREF},
{"th.vlseg5bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG5E8V,
    MASK_VLSEG5E8V, match_opcode, INSN_DREF},
{"th.vlseg5hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG5E16V,
    MASK_VLSEG5E16V, match_opcode, INSN_DREF},
{"th.vlseg5wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG5E32V,
    MASK_VLSEG5E32V, match_opcode, INSN_DREF},
{"th.vlseg5e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG5E64V,
    MASK_VLSEG5E64V, match_opcode, INSN_DREF},
{"th.vsseg5b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG5E8V,
    MASK_VSSEG5E8V, match_opcode, INSN_DREF},
{"th.vsseg5h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG5E16V,
    MASK_VSSEG5E16V, match_opcode, INSN_DREF},
{"th.vsseg5w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG5E32V,
    MASK_VSSEG5E32V, match_opcode, INSN_DREF},
{"th.vsseg5e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG5E64V,
    MASK_VSSEG5E64V, match_opcode, INSN_DREF},
{"th.vlseg6b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG6BV,
    MASK_TH_VLSEG6BV, match_opcode, INSN_DREF},
{"th.vlseg6h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG6HV,
    MASK_TH_VLSEG6HV, match_opcode, INSN_DREF},
{"th.vlseg6w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG6WV,
    MASK_TH_VLSEG6WV, match_opcode, INSN_DREF},
{"th.vlseg6bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG6E8V,
    MASK_VLSEG6E8V, match_opcode, INSN_DREF},
{"th.vlseg6hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG6E16V,
    MASK_VLSEG6E16V, match_opcode, INSN_DREF},
{"th.vlseg6wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG6E32V,
    MASK_VLSEG6E32V, match_opcode, INSN_DREF},
{"th.vlseg6e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG6E64V,
    MASK_VLSEG6E64V, match_opcode, INSN_DREF},
{"th.vsseg6b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG6E8V,
    MASK_VSSEG6E8V, match_opcode, INSN_DREF},
{"th.vsseg6h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG6E16V,
    MASK_VSSEG6E16V, match_opcode, INSN_DREF},
{"th.vsseg6w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG6E32V,
    MASK_VSSEG6E32V, match_opcode, INSN_DREF},
{"th.vsseg6e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG6E64V,
    MASK_VSSEG6E64V, match_opcode, INSN_DREF},
{"th.vlseg7b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG7BV,
    MASK_TH_VLSEG7BV, match_opcode, INSN_DREF},
{"th.vlseg7h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG7HV,
    MASK_TH_VLSEG7HV, match_opcode, INSN_DREF},
{"th.vlseg7w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG7WV,
    MASK_TH_VLSEG7WV, match_opcode, INSN_DREF},
{"th.vlseg7bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG7E8V,
    MASK_VLSEG7E8V, match_opcode, INSN_DREF},
{"th.vlseg7hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG7E16V,
    MASK_VLSEG7E16V, match_opcode, INSN_DREF},
{"th.vlseg7wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG7E32V,
    MASK_VLSEG7E32V, match_opcode, INSN_DREF},
{"th.vlseg7e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG7E64V,
    MASK_VLSEG7E64V, match_opcode, INSN_DREF},
{"th.vsseg7b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG7E8V,
    MASK_VSSEG7E8V, match_opcode, INSN_DREF},
{"th.vsseg7h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG7E16V,
    MASK_VSSEG7E16V, match_opcode, INSN_DREF},
{"th.vsseg7w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG7E32V,
    MASK_VSSEG7E32V, match_opcode, INSN_DREF},
{"th.vsseg7e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG7E64V,
    MASK_VSSEG7E64V, match_opcode, INSN_DREF},
{"th.vlseg8b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG8BV,
    MASK_TH_VLSEG8BV, match_opcode, INSN_DREF},
{"th.vlseg8h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG8HV,
    MASK_TH_VLSEG8HV, match_opcode, INSN_DREF},
{"th.vlseg8w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_TH_VLSEG8WV,
    MASK_TH_VLSEG8WV, match_opcode, INSN_DREF},
{"th.vlseg8bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG8E8V,
    MASK_VLSEG8E8V, match_opcode, INSN_DREF},
{"th.vlseg8hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG8E16V,
    MASK_VLSEG8E16V, match_opcode, INSN_DREF},
{"th.vlseg8wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG8E32V,
    MASK_VLSEG8E32V, match_opcode, INSN_DREF},
{"th.vlseg8e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VLSEG8E64V,
    MASK_VLSEG8E64V, match_opcode, INSN_DREF},
{"th.vsseg8b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG8E8V,
    MASK_VSSEG8E8V, match_opcode, INSN_DREF},
{"th.vsseg8h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG8E16V,
    MASK_VSSEG8E16V, match_opcode, INSN_DREF},
{"th.vsseg8w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG8E32V,
    MASK_VSSEG8E32V, match_opcode, INSN_DREF},
{"th.vsseg8e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm", MATCH_VSSEG8E64V,
    MASK_VSSEG8E64V, match_opcode, INSN_DREF},
{"th.vlsseg2b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG2BV, MASK_TH_VLSSEG2BV, match_opcode, INSN_DREF},
{"th.vlsseg2h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG2HV, MASK_TH_VLSSEG2HV, match_opcode, INSN_DREF},
{"th.vlsseg2w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG2WV, MASK_TH_VLSSEG2WV, match_opcode, INSN_DREF},
{"th.vlsseg2bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG2E8V, MASK_VLSSEG2E8V, match_opcode, INSN_DREF},
{"th.vlsseg2hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG2E16V, MASK_VLSSEG2E16V, match_opcode, INSN_DREF},
{"th.vlsseg2wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG2E32V, MASK_VLSSEG2E32V, match_opcode, INSN_DREF},
{"th.vlsseg2e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG2E64V, MASK_VLSSEG2E64V, match_opcode, INSN_DREF},
{"th.vssseg2b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG2E8V, MASK_VSSSEG2E8V, match_opcode, INSN_DREF},
{"th.vssseg2h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG2E16V, MASK_VSSSEG2E16V, match_opcode, INSN_DREF},
{"th.vssseg2w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG2E32V, MASK_VSSSEG2E32V, match_opcode, INSN_DREF},
{"th.vssseg2e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG2E64V, MASK_VSSSEG2E64V, match_opcode, INSN_DREF},
{"th.vlsseg3b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG3BV, MASK_TH_VLSSEG3BV, match_opcode, INSN_DREF},
{"th.vlsseg3h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG3HV, MASK_TH_VLSSEG3HV, match_opcode, INSN_DREF},
{"th.vlsseg3w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG3WV, MASK_TH_VLSSEG3WV, match_opcode, INSN_DREF},
{"th.vlsseg3bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG3E8V, MASK_VLSSEG3E8V, match_opcode, INSN_DREF},
{"th.vlsseg3hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG3E16V, MASK_VLSSEG3E16V, match_opcode, INSN_DREF},
{"th.vlsseg3wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG3E32V, MASK_VLSSEG3E32V, match_opcode, INSN_DREF},
{"th.vlsseg3e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG3E64V, MASK_VLSSEG3E64V, match_opcode, INSN_DREF},
{"th.vssseg3b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG3E8V, MASK_VSSSEG3E8V, match_opcode, INSN_DREF},
{"th.vssseg3h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG3E16V, MASK_VSSSEG3E16V, match_opcode, INSN_DREF},
{"th.vssseg3w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG3E32V, MASK_VSSSEG3E32V, match_opcode, INSN_DREF},
{"th.vssseg3e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG3E64V, MASK_VSSSEG3E64V, match_opcode, INSN_DREF},
{"th.vlsseg4b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG4BV, MASK_TH_VLSSEG4BV, match_opcode, INSN_DREF},
{"th.vlsseg4h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG4HV, MASK_TH_VLSSEG4HV, match_opcode, INSN_DREF},
{"th.vlsseg4w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG4WV, MASK_TH_VLSSEG4WV, match_opcode, INSN_DREF},
{"th.vlsseg4bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG4E8V, MASK_VLSSEG4E8V, match_opcode, INSN_DREF},
{"th.vlsseg4hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG4E16V, MASK_VLSSEG4E16V, match_opcode, INSN_DREF},
{"th.vlsseg4wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG4E32V, MASK_VLSSEG4E32V, match_opcode, INSN_DREF},
{"th.vlsseg4e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG4E64V, MASK_VLSSEG4E64V, match_opcode, INSN_DREF},
{"th.vssseg4b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG4E8V, MASK_VSSSEG4E8V, match_opcode, INSN_DREF},
{"th.vssseg4h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG4E16V, MASK_VSSSEG4E16V, match_opcode, INSN_DREF},
{"th.vssseg4w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG4E32V, MASK_VSSSEG4E32V, match_opcode, INSN_DREF},
{"th.vssseg4e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG4E64V, MASK_VSSSEG4E64V, match_opcode, INSN_DREF},
{"th.vlsseg5b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG5BV, MASK_TH_VLSSEG5BV, match_opcode, INSN_DREF},
{"th.vlsseg5h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG5HV, MASK_TH_VLSSEG5HV, match_opcode, INSN_DREF},
{"th.vlsseg5w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG5WV, MASK_TH_VLSSEG5WV, match_opcode, INSN_DREF},
{"th.vlsseg5bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG5E8V, MASK_VLSSEG5E8V, match_opcode, INSN_DREF},
{"th.vlsseg5hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG5E16V, MASK_VLSSEG5E16V, match_opcode, INSN_DREF},
{"th.vlsseg5wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG5E32V, MASK_VLSSEG5E32V, match_opcode, INSN_DREF},
{"th.vlsseg5e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG5E64V, MASK_VLSSEG5E64V, match_opcode, INSN_DREF},
{"th.vssseg5b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG5E8V, MASK_VSSSEG5E8V, match_opcode, INSN_DREF},
{"th.vssseg5h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG5E16V, MASK_VSSSEG5E16V, match_opcode, INSN_DREF},
{"th.vssseg5w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG5E32V, MASK_VSSSEG5E32V, match_opcode, INSN_DREF},
{"th.vssseg5e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG5E64V, MASK_VSSSEG5E64V, match_opcode, INSN_DREF},
{"th.vlsseg6b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG6BV, MASK_TH_VLSSEG6BV, match_opcode, INSN_DREF},
{"th.vlsseg6h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG6HV, MASK_TH_VLSSEG6HV, match_opcode, INSN_DREF},
{"th.vlsseg6w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG6WV, MASK_TH_VLSSEG6WV, match_opcode, INSN_DREF},
{"th.vlsseg6bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG6E8V, MASK_VLSSEG6E8V, match_opcode, INSN_DREF},
{"th.vlsseg6hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG6E16V, MASK_VLSSEG6E16V, match_opcode, INSN_DREF},
{"th.vlsseg6wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG6E32V, MASK_VLSSEG6E32V, match_opcode, INSN_DREF},
{"th.vlsseg6e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG6E64V, MASK_VLSSEG6E64V, match_opcode, INSN_DREF},
{"th.vssseg6b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG6E8V, MASK_VSSSEG6E8V, match_opcode, INSN_DREF},
{"th.vssseg6h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG6E16V, MASK_VSSSEG6E16V, match_opcode, INSN_DREF},
{"th.vssseg6w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG6E32V, MASK_VSSSEG6E32V, match_opcode, INSN_DREF},
{"th.vssseg6e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG6E64V, MASK_VSSSEG6E64V, match_opcode, INSN_DREF},
{"th.vlsseg7b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG7BV, MASK_TH_VLSSEG7BV, match_opcode, INSN_DREF},
{"th.vlsseg7h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG7HV, MASK_TH_VLSSEG7HV, match_opcode, INSN_DREF},
{"th.vlsseg7w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG7WV, MASK_TH_VLSSEG7WV, match_opcode, INSN_DREF},
{"th.vlsseg7bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG7E8V, MASK_VLSSEG7E8V, match_opcode, INSN_DREF},
{"th.vlsseg7hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG7E16V, MASK_VLSSEG7E16V, match_opcode, INSN_DREF},
{"th.vlsseg7wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG7E32V, MASK_VLSSEG7E32V, match_opcode, INSN_DREF},
{"th.vlsseg7e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG7E64V, MASK_VLSSEG7E64V, match_opcode, INSN_DREF},
{"th.vssseg7b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG7E8V, MASK_VSSSEG7E8V, match_opcode, INSN_DREF},
{"th.vssseg7h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG7E16V, MASK_VSSSEG7E16V, match_opcode, INSN_DREF},
{"th.vssseg7w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG7E32V, MASK_VSSSEG7E32V, match_opcode, INSN_DREF},
{"th.vssseg7e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG7E64V, MASK_VSSSEG7E64V, match_opcode, INSN_DREF},
{"th.vlsseg8b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG8BV, MASK_TH_VLSSEG8BV, match_opcode, INSN_DREF},
{"th.vlsseg8h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG8HV, MASK_TH_VLSSEG8HV, match_opcode, INSN_DREF},
{"th.vlsseg8w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_TH_VLSSEG8WV, MASK_TH_VLSSEG8WV, match_opcode, INSN_DREF},
{"th.vlsseg8bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG8E8V, MASK_VLSSEG8E8V, match_opcode, INSN_DREF},
{"th.vlsseg8hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG8E16V, MASK_VLSSEG8E16V, match_opcode, INSN_DREF},
{"th.vlsseg8wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG8E32V, MASK_VLSSEG8E32V, match_opcode, INSN_DREF},
{"th.vlsseg8e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VLSSEG8E64V, MASK_VLSSEG8E64V, match_opcode, INSN_DREF},
{"th.vssseg8b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG8E8V, MASK_VSSSEG8E8V, match_opcode, INSN_DREF},
{"th.vssseg8h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG8E16V, MASK_VSSSEG8E16V, match_opcode, INSN_DREF},
{"th.vssseg8w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG8E32V, MASK_VSSSEG8E32V, match_opcode, INSN_DREF},
{"th.vssseg8e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),tVm",
    MATCH_VSSSEG8E64V, MASK_VSSSEG8E64V, match_opcode, INSN_DREF},
{"th.vlxseg2b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG2BV, MASK_TH_VLXSEG2BV, match_opcode, INSN_DREF},
{"th.vlxseg2h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG2HV, MASK_TH_VLXSEG2HV, match_opcode, INSN_DREF},
{"th.vlxseg2w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG2WV, MASK_TH_VLXSEG2WV, match_opcode, INSN_DREF},
{"th.vlxseg2bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG2EI8V, MASK_VLOXSEG2EI8V, match_opcode, INSN_DREF},
{"th.vlxseg2hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG2EI16V, MASK_VLOXSEG2EI16V, match_opcode, INSN_DREF},
{"th.vlxseg2wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG2EI32V, MASK_VLOXSEG2EI32V, match_opcode, INSN_DREF},
{"th.vlxseg2e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG2EI64V, MASK_VLOXSEG2EI64V, match_opcode, INSN_DREF},
{"th.vsxseg2b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG2EI8V, MASK_VSOXSEG2EI8V, match_opcode, INSN_DREF},
{"th.vsxseg2h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG2EI16V, MASK_VSOXSEG2EI16V, match_opcode, INSN_DREF},
{"th.vsxseg2w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG2EI32V, MASK_VSOXSEG2EI32V, match_opcode, INSN_DREF},
{"th.vsxseg2e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG2EI64V, MASK_VSOXSEG2EI64V, match_opcode, INSN_DREF},
{"th.vlxseg3b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG3BV, MASK_TH_VLXSEG3BV, match_opcode, INSN_DREF},
{"th.vlxseg3h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG3HV, MASK_TH_VLXSEG3HV, match_opcode, INSN_DREF},
{"th.vlxseg3w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG3WV, MASK_TH_VLXSEG3WV, match_opcode, INSN_DREF},
{"th.vlxseg3bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG3EI8V, MASK_VLOXSEG3EI8V, match_opcode, INSN_DREF},
{"th.vlxseg3hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG3EI16V, MASK_VLOXSEG3EI16V, match_opcode, INSN_DREF},
{"th.vlxseg3wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG3EI32V, MASK_VLOXSEG3EI32V, match_opcode, INSN_DREF},
{"th.vlxseg3e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG3EI64V, MASK_VLOXSEG3EI64V, match_opcode, INSN_DREF},
{"th.vsxseg3b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG3EI8V, MASK_VSOXSEG3EI8V, match_opcode, INSN_DREF},
{"th.vsxseg3h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG3EI16V, MASK_VSOXSEG3EI16V, match_opcode, INSN_DREF},
{"th.vsxseg3w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG3EI32V, MASK_VSOXSEG3EI32V, match_opcode, INSN_DREF},
{"th.vsxseg3e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG3EI64V, MASK_VSOXSEG3EI64V, match_opcode, INSN_DREF},
{"th.vlxseg4b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG4BV, MASK_TH_VLXSEG4BV, match_opcode, INSN_DREF},
{"th.vlxseg4h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG4HV, MASK_TH_VLXSEG4HV, match_opcode, INSN_DREF},
{"th.vlxseg4w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG4WV, MASK_TH_VLXSEG4WV, match_opcode, INSN_DREF},
{"th.vlxseg4bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG4EI8V, MASK_VLOXSEG4EI8V, match_opcode, INSN_DREF},
{"th.vlxseg4hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG4EI16V, MASK_VLOXSEG4EI16V, match_opcode, INSN_DREF},
{"th.vlxseg4wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG4EI32V, MASK_VLOXSEG4EI32V, match_opcode, INSN_DREF},
{"th.vlxseg4e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG4EI64V, MASK_VLOXSEG4EI64V, match_opcode, INSN_DREF},
{"th.vsxseg4b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG4EI8V, MASK_VSOXSEG4EI8V, match_opcode, INSN_DREF},
{"th.vsxseg4h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG4EI16V, MASK_VSOXSEG4EI16V, match_opcode, INSN_DREF},
{"th.vsxseg4w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG4EI32V, MASK_VSOXSEG4EI32V, match_opcode, INSN_DREF},
{"th.vsxseg4e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG4EI64V, MASK_VSOXSEG4EI64V, match_opcode, INSN_DREF},
{"th.vlxseg5b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG5BV, MASK_TH_VLXSEG5BV, match_opcode, INSN_DREF},
{"th.vlxseg5h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG5HV, MASK_TH_VLXSEG5HV, match_opcode, INSN_DREF},
{"th.vlxseg5w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG5WV, MASK_TH_VLXSEG5WV, match_opcode, INSN_DREF},
{"th.vlxseg5bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG5EI8V, MASK_VLOXSEG5EI8V, match_opcode, INSN_DREF},
{"th.vlxseg5hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG5EI16V, MASK_VLOXSEG5EI16V, match_opcode, INSN_DREF},
{"th.vlxseg5wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG5EI32V, MASK_VLOXSEG5EI32V, match_opcode, INSN_DREF},
{"th.vlxseg5e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG5EI64V, MASK_VLOXSEG5EI64V, match_opcode, INSN_DREF},
{"th.vsxseg5b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG5EI8V, MASK_VSOXSEG5EI8V, match_opcode, INSN_DREF},
{"th.vsxseg5h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG5EI16V, MASK_VSOXSEG5EI16V, match_opcode, INSN_DREF},
{"th.vsxseg5w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG5EI32V, MASK_VSOXSEG5EI32V, match_opcode, INSN_DREF},
{"th.vsxseg5e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG5EI64V, MASK_VSOXSEG5EI64V, match_opcode, INSN_DREF},
{"th.vlxseg6b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG6BV, MASK_TH_VLXSEG6BV, match_opcode, INSN_DREF},
{"th.vlxseg6h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG6HV, MASK_TH_VLXSEG6HV, match_opcode, INSN_DREF},
{"th.vlxseg6w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG6WV, MASK_TH_VLXSEG6WV, match_opcode, INSN_DREF},
{"th.vlxseg6bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG6EI8V, MASK_VLOXSEG6EI8V, match_opcode, INSN_DREF},
{"th.vlxseg6hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG6EI16V, MASK_VLOXSEG6EI16V, match_opcode, INSN_DREF},
{"th.vlxseg6wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG6EI32V, MASK_VLOXSEG6EI32V, match_opcode, INSN_DREF},
{"th.vlxseg6e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG6EI64V, MASK_VLOXSEG6EI64V, match_opcode, INSN_DREF},
{"th.vsxseg6b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG6EI8V, MASK_VSOXSEG6EI8V, match_opcode, INSN_DREF},
{"th.vsxseg6h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG6EI16V, MASK_VSOXSEG6EI16V, match_opcode, INSN_DREF},
{"th.vsxseg6w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG6EI32V, MASK_VSOXSEG6EI32V, match_opcode, INSN_DREF},
{"th.vsxseg6e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG6EI64V, MASK_VSOXSEG6EI64V, match_opcode, INSN_DREF},
{"th.vlxseg7b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG7BV, MASK_TH_VLXSEG7BV, match_opcode, INSN_DREF},
{"th.vlxseg7h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG7HV, MASK_TH_VLXSEG7HV, match_opcode, INSN_DREF},
{"th.vlxseg7w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG7WV, MASK_TH_VLXSEG7WV, match_opcode, INSN_DREF},
{"th.vlxseg7bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG7EI8V, MASK_VLOXSEG7EI8V, match_opcode, INSN_DREF},
{"th.vlxseg7hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG7EI16V, MASK_VLOXSEG7EI16V, match_opcode, INSN_DREF},
{"th.vlxseg7wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG7EI32V, MASK_VLOXSEG7EI32V, match_opcode, INSN_DREF},
{"th.vlxseg7e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG7EI64V, MASK_VLOXSEG7EI64V, match_opcode, INSN_DREF},
{"th.vsxseg7b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG7EI8V, MASK_VSOXSEG7EI8V, match_opcode, INSN_DREF},
{"th.vsxseg7h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG7EI16V, MASK_VSOXSEG7EI16V, match_opcode, INSN_DREF},
{"th.vsxseg7w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG7EI32V, MASK_VSOXSEG7EI32V, match_opcode, INSN_DREF},
{"th.vsxseg7e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG7EI64V, MASK_VSOXSEG7EI64V, match_opcode, INSN_DREF},
{"th.vlxseg8b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG8BV, MASK_TH_VLXSEG8BV, match_opcode, INSN_DREF},
{"th.vlxseg8h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG8HV, MASK_TH_VLXSEG8HV, match_opcode, INSN_DREF},
{"th.vlxseg8w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_TH_VLXSEG8WV, MASK_TH_VLXSEG8WV, match_opcode, INSN_DREF},
{"th.vlxseg8bu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG8EI8V, MASK_VLOXSEG8EI8V, match_opcode, INSN_DREF},
{"th.vlxseg8hu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG8EI16V, MASK_VLOXSEG8EI16V, match_opcode, INSN_DREF},
{"th.vlxseg8wu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG8EI32V, MASK_VLOXSEG8EI32V, match_opcode, INSN_DREF},
{"th.vlxseg8e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VLOXSEG8EI64V, MASK_VLOXSEG8EI64V, match_opcode, INSN_DREF},
{"th.vsxseg8b.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG8EI8V, MASK_VSOXSEG8EI8V, match_opcode, INSN_DREF},
{"th.vsxseg8h.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG8EI16V, MASK_VSOXSEG8EI16V, match_opcode, INSN_DREF},
{"th.vsxseg8w.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG8EI32V, MASK_VSOXSEG8EI32V, match_opcode, INSN_DREF},
{"th.vsxseg8e.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s),VtVm",
    MATCH_VSOXSEG8EI64V, MASK_VSOXSEG8EI64V, match_opcode, INSN_DREF},
{"th.vlseg2bff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG2BFFV, MASK_TH_VLSEG2BFFV, match_opcode, INSN_DREF},
{"th.vlseg2hff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG2HFFV, MASK_TH_VLSEG2HFFV, match_opcode, INSN_DREF},
{"th.vlseg2wff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG2WFFV, MASK_TH_VLSEG2WFFV, match_opcode, INSN_DREF},
{"th.vlseg2buff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG2E8FFV, MASK_VLSEG2E8FFV, match_opcode, INSN_DREF},
{"th.vlseg2huff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG2E16FFV, MASK_VLSEG2E16FFV, match_opcode, INSN_DREF},
{"th.vlseg2wuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG2E32FFV, MASK_VLSEG2E32FFV, match_opcode, INSN_DREF},
{"th.vlseg2eff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG2E64FFV, MASK_VLSEG2E64FFV, match_opcode, INSN_DREF},
{"th.vlseg3bff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG3BFFV, MASK_TH_VLSEG3BFFV, match_opcode, INSN_DREF},
{"th.vlseg3hff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG3HFFV, MASK_TH_VLSEG3HFFV, match_opcode, INSN_DREF},
{"th.vlseg3wff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG3WFFV, MASK_TH_VLSEG3WFFV, match_opcode, INSN_DREF},
{"th.vlseg3buff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG3E8FFV, MASK_VLSEG3E8FFV, match_opcode, INSN_DREF},
{"th.vlseg3huff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG3E16FFV, MASK_VLSEG3E16FFV, match_opcode, INSN_DREF},
{"th.vlseg3wuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG3E32FFV, MASK_VLSEG3E32FFV, match_opcode, INSN_DREF},
{"th.vlseg3eff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG3E64FFV, MASK_VLSEG3E64FFV, match_opcode, INSN_DREF},
{"th.vlseg4bff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG4BFFV, MASK_TH_VLSEG4BFFV, match_opcode, INSN_DREF},
{"th.vlseg4hff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG4HFFV, MASK_TH_VLSEG4HFFV, match_opcode, INSN_DREF},
{"th.vlseg4wff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG4WFFV, MASK_TH_VLSEG4WFFV, match_opcode, INSN_DREF},
{"th.vlseg4buff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG4E8FFV, MASK_VLSEG4E8FFV, match_opcode, INSN_DREF},
{"th.vlseg4huff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG4E16FFV, MASK_VLSEG4E16FFV, match_opcode, INSN_DREF},
{"th.vlseg4wuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG4E32FFV, MASK_VLSEG4E32FFV, match_opcode, INSN_DREF},
{"th.vlseg4eff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG4E64FFV, MASK_VLSEG4E64FFV, match_opcode, INSN_DREF},
{"th.vlseg5bff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG5BFFV, MASK_TH_VLSEG5BFFV, match_opcode, INSN_DREF},
{"th.vlseg5hff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG5HFFV, MASK_TH_VLSEG5HFFV, match_opcode, INSN_DREF},
{"th.vlseg5wff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG5WFFV, MASK_TH_VLSEG5WFFV, match_opcode, INSN_DREF},
{"th.vlseg5buff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG5E8FFV, MASK_VLSEG5E8FFV, match_opcode, INSN_DREF},
{"th.vlseg5huff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG5E16FFV, MASK_VLSEG5E16FFV, match_opcode, INSN_DREF},
{"th.vlseg5wuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG5E32FFV, MASK_VLSEG5E32FFV, match_opcode, INSN_DREF},
{"th.vlseg5eff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG5E64FFV, MASK_VLSEG5E64FFV, match_opcode, INSN_DREF},
{"th.vlseg6bff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG6BFFV, MASK_TH_VLSEG6BFFV, match_opcode, INSN_DREF},
{"th.vlseg6hff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG6HFFV, MASK_TH_VLSEG6HFFV, match_opcode, INSN_DREF},
{"th.vlseg6wff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG6WFFV, MASK_TH_VLSEG6WFFV, match_opcode, INSN_DREF},
{"th.vlseg6buff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG6E8FFV, MASK_VLSEG6E8FFV, match_opcode, INSN_DREF},
{"th.vlseg6huff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG6E16FFV, MASK_VLSEG6E16FFV, match_opcode, INSN_DREF},
{"th.vlseg6wuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG6E32FFV, MASK_VLSEG6E32FFV, match_opcode, INSN_DREF},
{"th.vlseg6eff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG6E64FFV, MASK_VLSEG6E64FFV, match_opcode, INSN_DREF},
{"th.vlseg7bff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG7BFFV, MASK_TH_VLSEG7BFFV, match_opcode, INSN_DREF},
{"th.vlseg7hff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG7HFFV, MASK_TH_VLSEG7HFFV, match_opcode, INSN_DREF},
{"th.vlseg7wff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG7WFFV, MASK_TH_VLSEG7WFFV, match_opcode, INSN_DREF},
{"th.vlseg7buff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG7E8FFV, MASK_VLSEG7E8FFV, match_opcode, INSN_DREF},
{"th.vlseg7huff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG7E16FFV, MASK_VLSEG7E16FFV, match_opcode, INSN_DREF},
{"th.vlseg7wuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG7E32FFV, MASK_VLSEG7E32FFV, match_opcode, INSN_DREF},
{"th.vlseg7eff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG7E64FFV, MASK_VLSEG7E64FFV, match_opcode, INSN_DREF},
{"th.vlseg8bff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG8BFFV, MASK_TH_VLSEG8BFFV, match_opcode, INSN_DREF},
{"th.vlseg8hff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG8HFFV, MASK_TH_VLSEG8HFFV, match_opcode, INSN_DREF},
{"th.vlseg8wff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_TH_VLSEG8WFFV, MASK_TH_VLSEG8WFFV, match_opcode, INSN_DREF},
{"th.vlseg8buff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG8E8FFV, MASK_VLSEG8E8FFV, match_opcode, INSN_DREF},
{"th.vlseg8huff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG8E16FFV, MASK_VLSEG8E16FFV, match_opcode, INSN_DREF},
{"th.vlseg8wuff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG8E32FFV, MASK_VLSEG8E32FFV, match_opcode, INSN_DREF},
{"th.vlseg8eff.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,0(s)Vm",
    MATCH_VLSEG8E64FFV, MASK_VLSEG8E64FFV, match_opcode, INSN_DREF},
{"th.vamoaddw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOADDWV, MASK_TH_VAMOADDWV, match_opcode, INSN_DREF},
{"th.vamoaddd.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOADDDV, MASK_TH_VAMOADDDV, match_opcode, INSN_DREF},
{"th.vamoswapw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOSWAPWV, MASK_TH_VAMOSWAPWV, match_opcode, INSN_DREF},
{"th.vamoswapd.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOSWAPDV, MASK_TH_VAMOSWAPDV, match_opcode, INSN_DREF},
{"th.vamoxorw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOXORWV, MASK_TH_VAMOXORWV, match_opcode, INSN_DREF},
{"th.vamoxord.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOXORDV, MASK_TH_VAMOXORDV, match_opcode, INSN_DREF},
{"th.vamoandw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOANDWV, MASK_TH_VAMOANDWV, match_opcode, INSN_DREF},
{"th.vamoandd.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOANDDV, MASK_TH_VAMOANDDV, match_opcode, INSN_DREF},
{"th.vamoorw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOORWV, MASK_TH_VAMOORWV, match_opcode, INSN_DREF},
{"th.vamoord.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOORDV, MASK_TH_VAMOORDV, match_opcode, INSN_DREF},
{"th.vamominw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMINWV, MASK_TH_VAMOMINWV, match_opcode, INSN_DREF},
{"th.vamomind.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMINDV, MASK_TH_VAMOMINDV, match_opcode, INSN_DREF},
{"th.vamomaxw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMAXWV, MASK_TH_VAMOMAXWV, match_opcode, INSN_DREF},
{"th.vamomaxd.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMAXDV, MASK_TH_VAMOMAXDV, match_opcode, INSN_DREF},
{"th.vamominuw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMINUWV, MASK_TH_VAMOMINUWV, match_opcode, INSN_DREF},
{"th.vamominud.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMINUDV, MASK_TH_VAMOMINUDV, match_opcode, INSN_DREF},
{"th.vamomaxuw.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMAXUWV, MASK_TH_VAMOMAXUWV, match_opcode, INSN_DREF},
{"th.vamomaxud.v", 0, INSN_CLASS_XTHEADZVAMO, "Ve,Vt,(s),VfVm",
    MATCH_TH_VAMOMAXUDV, MASK_TH_VAMOMAXUDV, match_opcode, INSN_DREF},
{"th.vneg.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_VRSUBVX,
    MASK_VRSUBVX | MASK_RS1, match_opcode, INSN_ALIAS},
{"th.vadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VADDVV,
    MASK_VADDVV, match_opcode, 0},
{"th.vadd.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VADDVX,
    MASK_VADDVX, match_opcode, 0},
{"th.vadd.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VADDVI,
    MASK_VADDVI, match_opcode, 0},
{"th.vsub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSUBVV,
    MASK_VSUBVV, match_opcode, 0},
{"th.vsub.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSUBVX,
    MASK_VSUBVX, match_opcode, 0},
{"th.vrsub.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VRSUBVX,
    MASK_VRSUBVX, match_opcode, 0},
{"th.vrsub.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VRSUBVI,
    MASK_VRSUBVI, match_opcode, 0},
{"th.vwcvt.x.x.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_VWCVTXXV,
    MASK_VWCVTXXV, match_opcode, INSN_ALIAS},
{"th.vwcvtu.x.x.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_VWCVTUXXV,
    MASK_VWCVTUXXV, match_opcode, INSN_ALIAS},
{"th.vwaddu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWADDUVV,
    MASK_VWADDUVV, match_opcode, 0},
{"th.vwaddu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWADDUVX,
    MASK_VWADDUVX, match_opcode, 0},
{"th.vwsubu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWSUBUVV,
    MASK_VWSUBUVV, match_opcode, 0},
{"th.vwsubu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWSUBUVX,
    MASK_VWSUBUVX, match_opcode, 0},
{"th.vwadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWADDVV,
    MASK_VWADDVV, match_opcode, 0},
{"th.vwadd.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWADDVX,
    MASK_VWADDVX, match_opcode, 0},
{"th.vwsub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWSUBVV,
    MASK_VWSUBVV, match_opcode, 0},
{"th.vwsub.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWSUBVX,
    MASK_VWSUBVX, match_opcode, 0},
{"th.vwaddu.wv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWADDUWV,
    MASK_VWADDUWV, match_opcode, 0},
{"th.vwaddu.wx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWADDUWX,
    MASK_VWADDUWX, match_opcode, 0},
{"th.vwsubu.wv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWSUBUWV,
    MASK_VWSUBUWV, match_opcode, 0},
{"th.vwsubu.wx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWSUBUWX,
    MASK_VWSUBUWX, match_opcode, 0},
{"th.vwadd.wv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWADDWV,
    MASK_VWADDWV, match_opcode, 0},
{"th.vwadd.wx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWADDWX,
    MASK_VWADDWX, match_opcode, 0},
{"th.vwsub.wv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWSUBWV,
    MASK_VWSUBWV, match_opcode, 0},
{"th.vwsub.wx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWSUBWX,
    MASK_VWSUBWX, match_opcode, 0},
{"th.vadc.vvm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs,V0", MATCH_TH_VADCVVM,
    MASK_TH_VADCVVM, match_opcode, 0},
{"th.vadc.vxm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,s,V0", MATCH_TH_VADCVXM,
    MASK_TH_VADCVXM, match_opcode, 0},
{"th.vadc.vim", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vi,V0", MATCH_TH_VADCVIM,
    MASK_TH_VADCVIM, match_opcode, 0},
{"th.vmadc.vvm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs,V0", MATCH_VMADCVV,
    MASK_VMADCVV, match_opcode, 0},
{"th.vmadc.vxm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,s,V0", MATCH_VMADCVX,
    MASK_VMADCVX, match_opcode, 0},
{"th.vmadc.vim", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vi,V0", MATCH_VMADCVI,
    MASK_VMADCVI, match_opcode, 0},
{"th.vsbc.vvm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs,V0", MATCH_TH_VSBCVVM,
    MASK_TH_VSBCVVM, match_opcode, 0},
{"th.vsbc.vxm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,s,V0", MATCH_TH_VSBCVXM,
    MASK_TH_VSBCVXM, match_opcode, 0},
{"th.vmsbc.vvm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs,V0", MATCH_VMSBCVV,
    MASK_VMSBCVV, match_opcode, 0},
{"th.vmsbc.vxm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,s,V0", MATCH_VMSBCVX,
    MASK_VMSBCVX, match_opcode, 0},
{"th.vnot.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_VNOTV,
    MASK_VNOTV, match_opcode, INSN_ALIAS},
{"th.vand.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VANDVV,
    MASK_VANDVV, match_opcode, 0},
{"th.vand.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VANDVX,
    MASK_VANDVX, match_opcode, 0},
{"th.vand.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VANDVI,
    MASK_VANDVI, match_opcode, 0},
{"th.vor.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VORVV,
    MASK_VORVV, match_opcode, 0},
{"th.vor.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VORVX,
    MASK_VORVX, match_opcode, 0},
{"th.vor.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VORVI,
    MASK_VORVI, match_opcode, 0},
{"th.vxor.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VXORVV,
    MASK_VXORVV, match_opcode, 0},
{"th.vxor.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VXORVX,
    MASK_VXORVX, match_opcode, 0},
{"th.vxor.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VXORVI,
    MASK_VXORVI, match_opcode, 0},
{"th.vsll.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSLLVV,
    MASK_VSLLVV, match_opcode, 0},
{"th.vsll.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSLLVX,
    MASK_VSLLVX, match_opcode, 0},
{"th.vsll.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VSLLVI,
    MASK_VSLLVI, match_opcode, 0},
{"th.vsrl.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSRLVV,
    MASK_VSRLVV, match_opcode, 0},
{"th.vsrl.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSRLVX,
    MASK_VSRLVX, match_opcode, 0},
{"th.vsrl.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VSRLVI,
    MASK_VSRLVI, match_opcode, 0},
{"th.vsra.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSRAVV,
    MASK_VSRAVV, match_opcode, 0},
{"th.vsra.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSRAVX,
    MASK_VSRAVX, match_opcode, 0},
{"th.vsra.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VSRAVI,
    MASK_VSRAVI, match_opcode, 0},
{"th.vncvt.x.x.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_VNCVTXXW,
    MASK_VNCVTXXW, match_opcode, INSN_ALIAS},
{"th.vnsrl.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VNSRLWV,
    MASK_VNSRLWV, match_opcode, 0},
{"th.vnsrl.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VNSRLWX,
    MASK_VNSRLWX, match_opcode, 0},
{"th.vnsrl.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VNSRLWI,
    MASK_VNSRLWI, match_opcode, 0},
{"th.vnsra.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VNSRAWV,
    MASK_VNSRAWV, match_opcode, 0},
{"th.vnsra.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VNSRAWX,
    MASK_VNSRAWX, match_opcode, 0},
{"th.vnsra.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VNSRAWI,
    MASK_VNSRAWI, match_opcode, 0},
{"th.vmseq.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMSEQVV,
    MASK_VMSEQVV, match_opcode, 0},
{"th.vmseq.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSEQVX,
    MASK_VMSEQVX, match_opcode, 0},
{"th.vmseq.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VMSEQVI,
    MASK_VMSEQVI, match_opcode, 0},
{"th.vmsne.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMSNEVV,
    MASK_VMSNEVV, match_opcode, 0},
{"th.vmsne.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSNEVX,
    MASK_VMSNEVX, match_opcode, 0},
{"th.vmsne.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VMSNEVI,
    MASK_VMSNEVI, match_opcode, 0},
{"th.vmsltu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMSLTUVV,
    MASK_VMSLTUVV, match_opcode, 0},
{"th.vmsltu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSLTUVX,
    MASK_VMSLTUVX, match_opcode, 0},
{"th.vmslt.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMSLTVV,
    MASK_VMSLTVV, match_opcode, 0},
{"th.vmslt.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSLTVX,
    MASK_VMSLTVX, match_opcode, 0},
{"th.vmsleu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMSLEUVV,
    MASK_VMSLEUVV, match_opcode, 0},
{"th.vmsleu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSLEUVX,
    MASK_VMSLEUVX, match_opcode, 0},
{"th.vmsleu.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VMSLEUVI,
    MASK_VMSLEUVI, match_opcode, 0},
{"th.vmsle.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMSLEVV,
    MASK_VMSLEVV, match_opcode, 0},
{"th.vmsle.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSLEVX,
    MASK_VMSLEVX, match_opcode, 0},
{"th.vmsle.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VMSLEVI,
    MASK_VMSLEVI, match_opcode, 0},
{"th.vmsgtu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSGTUVX,
    MASK_VMSGTUVX, match_opcode, 0},
{"th.vmsgtu.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VMSGTUVI,
    MASK_VMSGTUVI, match_opcode, 0},
{"th.vmsgt.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMSGTVX,
    MASK_VMSGTVX, match_opcode, 0},
{"th.vmsgt.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VMSGTVI,
    MASK_VMSGTVI, match_opcode, 0},
{"th.vmsgt.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMSLTVV,
    MASK_VMSLTVV, match_opcode, INSN_ALIAS},
{"th.vmsgtu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMSLTUVV,
    MASK_VMSLTUVV, match_opcode, INSN_ALIAS},
{"th.vmsge.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMSLEVV,
    MASK_VMSLEVV, match_opcode, INSN_ALIAS},
{"th.vmsgeu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMSLEUVV,
    MASK_VMSLEUVV, match_opcode, INSN_ALIAS},
{"th.vmslt.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VkVm", MATCH_VMSLEVI,
    MASK_VMSLEVI, match_opcode, INSN_ALIAS},
{"th.vmsltu.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VkVm", MATCH_VMSLEUVI,
    MASK_VMSLEUVI, match_opcode, INSN_ALIAS},
{"th.vmsge.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VkVm", MATCH_VMSGTVI,
    MASK_VMSGTVI, match_opcode, INSN_ALIAS},
{"th.vmsgeu.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VkVm", MATCH_VMSGTUVI,
    MASK_VMSGTUVI, match_opcode, INSN_ALIAS},
{"th.vmsge.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", 0, (int)M_VMSGE,
    NULL, INSN_MACRO},
{"th.vmsge.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,s,VM,VT", 0,
    (int)M_VMSGE, NULL, INSN_MACRO},
{"th.vmsgeu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", 1, (int)M_VMSGE,
    NULL, INSN_MACRO},
{"th.vmsgeu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,s,VM,VT", 1,
    (int)M_VMSGE, NULL, INSN_MACRO},
{"th.vminu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMINUVV,
    MASK_VMINUVV, match_opcode, 0},
{"th.vminu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMINUVX,
    MASK_VMINUVX, match_opcode, 0},
{"th.vmin.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMINVV,
    MASK_VMINVV, match_opcode, 0},
{"th.vmin.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMINVX,
    MASK_VMINVX, match_opcode, 0},
{"th.vmaxu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMAXUVV,
    MASK_VMAXUVV, match_opcode, 0},
{"th.vmaxu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMAXUVX,
    MASK_VMAXUVX, match_opcode, 0},
{"th.vmax.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMAXVV,
    MASK_VMAXVV, match_opcode, 0},
{"th.vmax.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMAXVX,
    MASK_VMAXVX, match_opcode, 0},
{"th.vmul.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMULVV,
    MASK_VMULVV, match_opcode, 0},
{"th.vmul.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMULVX,
    MASK_VMULVX, match_opcode, 0},
{"th.vmulh.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMULHVV,
    MASK_VMULHVV, match_opcode, 0},
{"th.vmulh.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMULHVX,
    MASK_VMULHVX, match_opcode, 0},
{"th.vmulhu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMULHUVV,
    MASK_VMULHUVV, match_opcode, 0},
{"th.vmulhu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMULHUVX,
    MASK_VMULHUVX, match_opcode, 0},
{"th.vmulhsu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMULHSUVV,
    MASK_VMULHSUVV, match_opcode, 0},
{"th.vmulhsu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VMULHSUVX,
    MASK_VMULHSUVX, match_opcode, 0},
{"th.vwmul.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWMULVV,
    MASK_VWMULVV, match_opcode, 0},
{"th.vwmul.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWMULVX,
    MASK_VWMULVX, match_opcode, 0},
{"th.vwmulu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWMULUVV,
    MASK_VWMULUVV, match_opcode, 0},
{"th.vwmulu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWMULUVX,
    MASK_VWMULUVX, match_opcode, 0},
{"th.vwmulsu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VWMULSUVV,
    MASK_VWMULSUVV, match_opcode, 0},
{"th.vwmulsu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VWMULSUVX,
    MASK_VWMULSUVX, match_opcode, 0},
{"th.vmacc.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMACCVV,
    MASK_VMACCVV, match_opcode, 0},
{"th.vmacc.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VMACCVX,
    MASK_VMACCVX, match_opcode, 0},
{"th.vnmsac.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VNMSACVV,
    MASK_VNMSACVV, match_opcode, 0},
{"th.vnmsac.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VNMSACVX,
    MASK_VNMSACVX, match_opcode, 0},
{"th.vmadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMADDVV,
    MASK_VMADDVV, match_opcode, 0},
{"th.vmadd.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VMADDVX,
    MASK_VMADDVX, match_opcode, 0},
{"th.vnmsub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VNMSUBVV,
    MASK_VNMSUBVV, match_opcode, 0},
{"th.vnmsub.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VNMSUBVX,
    MASK_VNMSUBVX, match_opcode, 0},
{"th.vwmaccu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VWMACCUVV,
    MASK_VWMACCUVV, match_opcode, 0},
{"th.vwmaccu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VWMACCUVX,
    MASK_VWMACCUVX, match_opcode, 0},
{"th.vwmacc.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VWMACCVV,
    MASK_VWMACCVV, match_opcode, 0},
{"th.vwmacc.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VWMACCVX,
    MASK_VWMACCVX, match_opcode, 0},
{"th.vwmaccsu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm",
    MATCH_TH_VWMACCSUVV, MASK_TH_VWMACCSUVV, match_opcode, 0},
{"th.vwmaccsu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm",
    MATCH_VWMACCUSVX, MASK_VWMACCUSVX, match_opcode, 0},
{"th.vwmaccus.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm",
    MATCH_VWMACCSUVX, MASK_VWMACCSUVX, match_opcode, 0},
{"th.vdivu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VDIVUVV,
    MASK_VDIVUVV, match_opcode, 0},
{"th.vdivu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VDIVUVX,
    MASK_VDIVUVX, match_opcode, 0},
{"th.vdiv.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VDIVVV,
    MASK_VDIVVV, match_opcode, 0},
{"th.vdiv.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VDIVVX,
    MASK_VDIVVX, match_opcode, 0},
{"th.vremu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREMUVV,
    MASK_VREMUVV, match_opcode, 0},
{"th.vremu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VREMUVX,
    MASK_VREMUVX, match_opcode, 0},
{"th.vrem.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREMVV,
    MASK_VREMVV, match_opcode, 0},
{"th.vrem.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VREMVX,
    MASK_VREMVX, match_opcode, 0},
{"th.vmerge.vvm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs,V0",
    MATCH_VMERGEVVM, MASK_VMERGEVVM, match_opcode, 0},
{"th.vmerge.vxm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,s,V0", MATCH_VMERGEVXM,
    MASK_VMERGEVXM, match_opcode, 0},
{"th.vmerge.vim", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vi,V0",
    MATCH_VMERGEVIM, MASK_VMERGEVIM, match_opcode, 0},
{"th.vmv.v.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs", MATCH_VMVVV, MASK_VMVVV,
    match_opcode, 0},
{"th.vmv.v.x", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s", MATCH_VMVVX, MASK_VMVVX,
    match_opcode, 0},
{"th.vmv.v.i", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vi", MATCH_VMVVI, MASK_VMVVI,
    match_opcode, 0},
{"th.vsaddu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSADDUVV,
    MASK_VSADDUVV, match_opcode, 0},
{"th.vsaddu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSADDUVX,
    MASK_VSADDUVX, match_opcode, 0},
{"th.vsaddu.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VSADDUVI,
    MASK_VSADDUVI, match_opcode, 0},
{"th.vsadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSADDVV,
    MASK_VSADDVV, match_opcode, 0},
{"th.vsadd.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSADDVX,
    MASK_VSADDVX, match_opcode, 0},
{"th.vsadd.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_VSADDVI,
    MASK_VSADDVI, match_opcode, 0},
{"th.vssubu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSSUBUVV,
    MASK_VSSUBUVV, match_opcode, 0},
{"th.vssubu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSSUBUVX,
    MASK_VSSUBUVX, match_opcode, 0},
{"th.vssub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSSUBVV,
    MASK_VSSUBVV, match_opcode, 0},
{"th.vssub.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSSUBVX,
    MASK_VSSUBVX, match_opcode, 0},
{"th.vaadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_TH_VAADDVV,
    MASK_TH_VAADDVV, match_opcode, 0},
{"th.vaadd.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_TH_VAADDVX,
    MASK_TH_VAADDVX, match_opcode, 0},
{"th.vaadd.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,ViVm", MATCH_TH_VAADDVI,
    MASK_TH_VAADDVI, match_opcode, 0},
{"th.vasub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_TH_VASUBVV,
    MASK_TH_VASUBVV, match_opcode, 0},
{"th.vasub.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_TH_VASUBVX,
    MASK_TH_VASUBVX, match_opcode, 0},
{"th.vsmul.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSMULVV,
    MASK_VSMULVV, match_opcode, 0},
{"th.vsmul.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSMULVX,
    MASK_VSMULVX, match_opcode, 0},
{"th.vwsmaccu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm",
    MATCH_VQMACCUVV, MASK_VQMACCUVV, match_opcode, 0},
{"th.vwsmaccu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VQMACCUVX,
    MASK_VQMACCUVX, match_opcode, 0},
{"th.vwsmacc.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VQMACCVV,
    MASK_VQMACCVV, match_opcode, 0},
{"th.vwsmacc.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm", MATCH_VQMACCVX,
    MASK_VQMACCVX, match_opcode, 0},
{"th.vwsmaccsu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm",
    MATCH_TH_VWSMACCSUVV, MASK_TH_VWSMACCSUVV, match_opcode, 0},
{"th.vwsmaccsu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm",
    MATCH_VQMACCUSVX, MASK_VQMACCUSVX, match_opcode, 0},
{"th.vwsmaccus.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s,VtVm",
    MATCH_VQMACCSUVX, MASK_VQMACCSUVX, match_opcode, 0},
{"th.vssrl.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSSRLVV,
    MASK_VSSRLVV, match_opcode, 0},
{"th.vssrl.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSSRLVX,
    MASK_VSSRLVX, match_opcode, 0},
{"th.vssrl.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VSSRLVI,
    MASK_VSSRLVI, match_opcode, 0},
{"th.vssra.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VSSRAVV,
    MASK_VSSRAVV, match_opcode, 0},
{"th.vssra.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VSSRAVX,
    MASK_VSSRAVX, match_opcode, 0},
{"th.vssra.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VSSRAVI,
    MASK_VSSRAVI, match_opcode, 0},
{"th.vnclipu.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VNCLIPUWV,
    MASK_VNCLIPUWV, match_opcode, 0},
{"th.vnclipu.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VNCLIPUWX,
    MASK_VNCLIPUWX, match_opcode, 0},
{"th.vnclipu.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VNCLIPUWI,
    MASK_VNCLIPUWI, match_opcode, 0},
{"th.vnclip.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VNCLIPWV,
    MASK_VNCLIPWV, match_opcode, 0},
{"th.vnclip.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm", MATCH_VNCLIPWX,
    MASK_VNCLIPWX, match_opcode, 0},
{"th.vnclip.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm", MATCH_VNCLIPWI,
    MASK_VNCLIPWI, match_opcode, 0},
{"th.vfadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFADDVV,
    MASK_VFADDVV, match_opcode, 0},
{"th.vfadd.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFADDVF,
    MASK_VFADDVF, match_opcode, 0},
{"th.vfsub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFSUBVV,
    MASK_VFSUBVV, match_opcode, 0},
{"th.vfsub.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFSUBVF,
    MASK_VFSUBVF, match_opcode, 0},
{"th.vfrsub.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFRSUBVF,
    MASK_VFRSUBVF, match_opcode, 0},
{"th.vfwadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFWADDVV,
    MASK_VFWADDVV, match_opcode, 0},
{"th.vfwadd.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFWADDVF,
    MASK_VFWADDVF, match_opcode, 0},
{"th.vfwsub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFWSUBVV,
    MASK_VFWSUBVV, match_opcode, 0},
{"th.vfwsub.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFWSUBVF,
    MASK_VFWSUBVF, match_opcode, 0},
{"th.vfwadd.wv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFWADDWV,
    MASK_VFWADDWV, match_opcode, 0},
{"th.vfwsub.wv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFWSUBWV,
    MASK_VFWSUBWV, match_opcode, 0},
{"th.vfwadd.wf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFWADDWF,
    MASK_VFWADDWF, match_opcode, 0},
{"th.vfwsub.wf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFWSUBWF,
    MASK_VFWSUBWF, match_opcode, 0},
{"th.vfmul.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFMULVV,
    MASK_VFMULVV, match_opcode, 0},
{"th.vfmul.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFMULVF,
    MASK_VFMULVF, match_opcode, 0},
{"th.vfdiv.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFDIVVV,
    MASK_VFDIVVV, match_opcode, 0},
{"th.vfdiv.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFDIVVF,
    MASK_VFDIVVF, match_opcode, 0},
{"th.vfrdiv.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFRDIVVF,
    MASK_VFRDIVVF, match_opcode, 0},
{"th.vfwmul.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFWMULVV,
    MASK_VFWMULVV, match_opcode, 0},
{"th.vfwmul.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFWMULVF,
    MASK_VFWMULVF, match_opcode, 0},
{"th.vfmadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFMADDVV,
    MASK_VFMADDVV, match_opcode, 0},
{"th.vfmadd.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFMADDVF,
    MASK_VFMADDVF, match_opcode, 0},
{"th.vfnmadd.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFNMADDVV,
    MASK_VFNMADDVV, match_opcode, 0},
{"th.vfnmadd.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFNMADDVF,
    MASK_VFNMADDVF, match_opcode, 0},
{"th.vfmsub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFMSUBVV,
    MASK_VFMSUBVV, match_opcode, 0},
{"th.vfmsub.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFMSUBVF,
    MASK_VFMSUBVF, match_opcode, 0},
{"th.vfnmsub.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFNMSUBVV,
    MASK_VFNMSUBVV, match_opcode, 0},
{"th.vfnmsub.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFNMSUBVF,
    MASK_VFNMSUBVF, match_opcode, 0},
{"th.vfmacc.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFMACCVV,
    MASK_VFMACCVV, match_opcode, 0},
{"th.vfmacc.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFMACCVF,
    MASK_VFMACCVF, match_opcode, 0},
{"th.vfnmacc.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFNMACCVV,
    MASK_VFNMACCVV, match_opcode, 0},
{"th.vfnmacc.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFNMACCVF,
    MASK_VFNMACCVF, match_opcode, 0},
{"th.vfmsac.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFMSACVV,
    MASK_VFMSACVV, match_opcode, 0},
{"th.vfmsac.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFMSACVF,
    MASK_VFMSACVF, match_opcode, 0},
{"th.vfnmsac.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFNMSACVV,
    MASK_VFNMSACVV, match_opcode, 0},
{"th.vfnmsac.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFNMSACVF,
    MASK_VFNMSACVF, match_opcode, 0},
{"th.vfwmacc.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFWMACCVV,
    MASK_VFWMACCVV, match_opcode, 0},
{"th.vfwmacc.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFWMACCVF,
    MASK_VFWMACCVF, match_opcode, 0},
{"th.vfwnmacc.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm",
    MATCH_VFWNMACCVV, MASK_VFWNMACCVV, match_opcode, 0},
{"th.vfwnmacc.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm",
    MATCH_VFWNMACCVF, MASK_VFWNMACCVF, match_opcode, 0},
{"th.vfwmsac.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VFWMSACVV,
    MASK_VFWMSACVV, match_opcode, 0},
{"th.vfwmsac.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm", MATCH_VFWMSACVF,
    MASK_VFWMSACVF, match_opcode, 0},
{"th.vfwnmsac.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm",
    MATCH_VFWNMSACVV, MASK_VFWNMSACVV, match_opcode, 0},
{"th.vfwnmsac.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S,VtVm",
    MATCH_VFWNMSACVF, MASK_VFWNMSACVF, match_opcode, 0},
{"th.vfsqrt.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VFSQRTV,
    MASK_TH_VFSQRTV, match_opcode, 0},
{"th.vfmin.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFMINVV,
    MASK_VFMINVV, match_opcode, 0},
{"th.vfmin.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFMINVF,
    MASK_VFMINVF, match_opcode, 0},
{"th.vfmax.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFMAXVV,
    MASK_VFMAXVV, match_opcode, 0},
{"th.vfmax.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFMAXVF,
    MASK_VFMAXVF, match_opcode, 0},
{"th.vfneg.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VuVm", MATCH_VFSGNJNVV,
    MASK_VFSGNJNVV, match_vs1_eq_vs2, INSN_ALIAS},
{"th.vfabs.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VuVm", MATCH_VFSGNJXVV,
    MASK_VFSGNJXVV, match_vs1_eq_vs2, INSN_ALIAS},
{"th.vfsgnj.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFSGNJVV,
    MASK_VFSGNJVV, match_opcode, 0},
{"th.vfsgnj.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFSGNJVF,
    MASK_VFSGNJVF, match_opcode, 0},
{"th.vfsgnjn.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFSGNJNVV,
    MASK_VFSGNJNVV, match_opcode, 0},
{"th.vfsgnjn.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFSGNJNVF,
    MASK_VFSGNJNVF, match_opcode, 0},
{"th.vfsgnjx.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VFSGNJXVV,
    MASK_VFSGNJXVV, match_opcode, 0},
{"th.vfsgnjx.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VFSGNJXVF,
    MASK_VFSGNJXVF, match_opcode, 0},
{"th.vmfeq.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMFEQVV,
    MASK_VMFEQVV, match_opcode, 0},
{"th.vmfeq.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VMFEQVF,
    MASK_VMFEQVF, match_opcode, 0},
{"th.vmfne.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMFNEVV,
    MASK_VMFNEVV, match_opcode, 0},
{"th.vmfne.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VMFNEVF,
    MASK_VMFNEVF, match_opcode, 0},
{"th.vmflt.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMFLTVV,
    MASK_VMFLTVV, match_opcode, 0},
{"th.vmflt.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VMFLTVF,
    MASK_VMFLTVF, match_opcode, 0},
{"th.vmfle.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VMFLEVV,
    MASK_VMFLEVV, match_opcode, 0},
{"th.vmfle.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VMFLEVF,
    MASK_VMFLEVF, match_opcode, 0},
{"th.vmfgt.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VMFGTVF,
    MASK_VMFGTVF, match_opcode, 0},
{"th.vmfge.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_VMFGEVF,
    MASK_VMFGEVF, match_opcode, 0},
{"th.vmfgt.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMFLTVV,
    MASK_VMFLTVV, match_opcode, INSN_ALIAS},
{"th.vmfge.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vs,VtVm", MATCH_VMFLEVV,
    MASK_VMFLEVV, match_opcode, INSN_ALIAS},
{"th.vmford.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_TH_VMFORDVV, MASK_TH_VMFORDVV, match_opcode, 0},
{"th.vmford.vf", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,SVm", MATCH_TH_VMFORDVF,
    MASK_TH_VMFORDVF, match_opcode, 0},
{"th.vfclass.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VFCLASSV,
    MASK_TH_VFCLASSV, match_opcode, 0},
{"th.vfmerge.vfm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,S,V0",
    MATCH_VFMERGEVFM, MASK_VFMERGEVFM, match_opcode, 0},
{"th.vfmv.v.f", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S", MATCH_VFMVVF,
    MASK_VFMVVF, match_opcode, 0},
{"th.vfcvt.xu.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFCVTXUFV, MASK_TH_VFCVTXUFV, match_opcode, 0},
{"th.vfcvt.x.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VFCVTXFV,
    MASK_TH_VFCVTXFV, match_opcode, 0},
{"th.vfcvt.f.xu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFCVTFXUV, MASK_TH_VFCVTFXUV, match_opcode, 0},
{"th.vfcvt.f.x.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VFCVTFXV,
    MASK_TH_VFCVTFXV, match_opcode, 0},
{"th.vfwcvt.xu.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFWCVTXUFV, MASK_TH_VFWCVTXUFV, match_opcode, 0},
{"th.vfwcvt.x.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFWCVTXFV, MASK_TH_VFWCVTXFV, match_opcode, 0},
{"th.vfwcvt.f.xu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFWCVTFXUV, MASK_TH_VFWCVTFXUV, match_opcode, 0},
{"th.vfwcvt.f.x.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFWCVTFXV, MASK_TH_VFWCVTFXV, match_opcode, 0},
{"th.vfwcvt.f.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFWCVTFFV, MASK_TH_VFWCVTFFV, match_opcode, 0},
{"th.vfncvt.xu.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFNCVTXUFV, MASK_TH_VFNCVTXUFV, match_opcode, 0},
{"th.vfncvt.x.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFNCVTXFV, MASK_TH_VFNCVTXFV, match_opcode, 0},
{"th.vfncvt.f.xu.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFNCVTFXUV, MASK_TH_VFNCVTFXUV, match_opcode, 0},
{"th.vfncvt.f.x.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFNCVTFXV, MASK_TH_VFNCVTFXV, match_opcode, 0},
{"th.vfncvt.f.f.v", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm",
    MATCH_TH_VFNCVTFFV, MASK_TH_VFNCVTFFV, match_opcode, 0},
{"th.vredsum.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREDSUMVS,
    MASK_VREDSUMVS, match_opcode, 0},
{"th.vredmaxu.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VREDMAXUVS, MASK_VREDMAXUVS, match_opcode, 0},
{"th.vredmax.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREDMAXVS,
    MASK_VREDMAXVS, match_opcode, 0},
{"th.vredminu.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VREDMINUVS, MASK_VREDMINUVS, match_opcode, 0},
{"th.vredmin.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREDMINVS,
    MASK_VREDMINVS, match_opcode, 0},
{"th.vredand.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREDANDVS,
    MASK_VREDANDVS, match_opcode, 0},
{"th.vredor.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREDORVS,
    MASK_VREDORVS, match_opcode, 0},
{"th.vredxor.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm", MATCH_VREDXORVS,
    MASK_VREDXORVS, match_opcode, 0},
{"th.vwredsumu.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VWREDSUMUVS, MASK_VWREDSUMUVS, match_opcode, 0},
{"th.vwredsum.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VWREDSUMVS, MASK_VWREDSUMVS, match_opcode, 0},
{"th.vfredosum.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VFREDOSUMVS, MASK_VFREDOSUMVS, match_opcode, 0},
{"th.vfredsum.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VFREDUSUMVS, MASK_VFREDUSUMVS, match_opcode, 0},
{"th.vfredmax.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VFREDMAXVS, MASK_VFREDMAXVS, match_opcode, 0},
{"th.vfredmin.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VFREDMINVS, MASK_VFREDMINVS, match_opcode, 0},
{"th.vfwredosum.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VFWREDOSUMVS, MASK_VFWREDOSUMVS, match_opcode, 0},
{"th.vfwredsum.vs", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VFWREDUSUMVS, MASK_VFWREDUSUMVS, match_opcode, 0},
{"th.vmcpy.m", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vu", MATCH_VMANDMM,
    MASK_VMANDMM, match_vs1_eq_vs2, INSN_ALIAS},
{"th.vmmv.m", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vu", MATCH_VMANDMM,
    MASK_VMANDMM, match_vs1_eq_vs2, INSN_ALIAS},
{"th.vmclr.m", 0, INSN_CLASS_XTHEADVECTOR, "Vv", MATCH_VMXORMM,
    MASK_VMXORMM, match_vd_eq_vs1_eq_vs2, INSN_ALIAS},
{"th.vmset.m", 0, INSN_CLASS_XTHEADVECTOR, "Vv", MATCH_VMXNORMM,
    MASK_VMXNORMM, match_vd_eq_vs1_eq_vs2, INSN_ALIAS},
{"th.vmnot.m", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vu", MATCH_VMNANDMM,
    MASK_VMNANDMM, match_vs1_eq_vs2, INSN_ALIAS},
{"th.vmand.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMANDMM,
    MASK_VMANDMM, match_opcode, 0},
{"th.vmnand.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMNANDMM,
    MASK_VMNANDMM, match_opcode, 0},
{"th.vmandnot.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMANDNMM,
    MASK_VMANDNMM, match_opcode, 0},
{"th.vmxor.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMXORMM,
    MASK_VMXORMM, match_opcode, 0},
{"th.vmor.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMORMM,
    MASK_VMORMM, match_opcode, 0},
{"th.vmnor.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMNORMM,
    MASK_VMNORMM, match_opcode, 0},
{"th.vmornot.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMORNMM,
    MASK_VMORNMM, match_opcode, 0},
{"th.vmxnor.mm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs", MATCH_VMXNORMM,
    MASK_VMXNORMM, match_opcode, 0},
{"th.vmpopc.m", 0, INSN_CLASS_XTHEADVECTOR, "d,VtVm", MATCH_TH_VMPOPCM,
    MASK_TH_VMPOPCM, match_opcode, 0},
{"th.vmfirst.m", 0, INSN_CLASS_XTHEADVECTOR, "d,VtVm", MATCH_TH_VMFIRSTM,
    MASK_TH_VMFIRSTM, match_opcode, 0},
{"th.vmsbf.m", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VMSBFM,
    MASK_TH_VMSBFM, match_opcode, 0},
{"th.vmsif.m", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VMSIFM,
    MASK_TH_VMSIFM, match_opcode, 0},
{"th.vmsof.m", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VMSOFM,
    MASK_TH_VMSOFM, match_opcode, 0},
{"th.viota.m", 0, INSN_CLASS_XTHEADVECTOR, "Vd,VtVm", MATCH_TH_VIOTAM,
    MASK_TH_VIOTAM, match_opcode, 0},
{"th.vid.v", 0, INSN_CLASS_XTHEADVECTOR, "VdVm", MATCH_TH_VIDV,
    MASK_TH_VIDV, match_opcode, 0},
{"th.vmv.x.s", 0, INSN_CLASS_XTHEADVECTOR, "d,Vt", MATCH_TH_VMVXS,
    MASK_TH_VMVXS, match_opcode, INSN_ALIAS},
{"th.vext.x.v", 0, INSN_CLASS_XTHEADVECTOR, "d,Vt,s", MATCH_TH_VEXTXV,
    MASK_TH_VEXTXV, match_opcode, 0},
{"th.vmv.s.x", 0, INSN_CLASS_XTHEADVECTOR, "Vd,s", MATCH_TH_VMVSX,
    MASK_TH_VMVSX, match_opcode, 0},
{"th.vfmv.f.s", 0, INSN_CLASS_XTHEADVECTOR, "D,Vt", MATCH_TH_VFMVFS,
    MASK_TH_VFMVFS, match_opcode, 0},
{"th.vfmv.s.f", 0, INSN_CLASS_XTHEADVECTOR, "Vd,S", MATCH_TH_VFMVSF,
    MASK_TH_VFMVSF, match_opcode, 0},
{"th.vslideup.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm",
    MATCH_VSLIDEUPVX, MASK_VSLIDEUPVX, match_opcode, 0},
{"th.vslideup.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm",
    MATCH_VSLIDEUPVI, MASK_VSLIDEUPVI, match_opcode, 0},
{"th.vslidedown.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm",
    MATCH_VSLIDEDOWNVX, MASK_VSLIDEDOWNVX, match_opcode, 0},
{"th.vslidedown.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm",
    MATCH_VSLIDEDOWNVI, MASK_VSLIDEDOWNVI, match_opcode, 0},
{"th.vslide1up.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm",
    MATCH_VSLIDE1UPVX, MASK_VSLIDE1UPVX, match_opcode, 0},
{"th.vslide1down.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm",
    MATCH_VSLIDE1DOWNVX, MASK_VSLIDE1DOWNVX, match_opcode, 0},
{"th.vrgather.vv", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VsVm",
    MATCH_VRGATHERVV, MASK_VRGATHERVV, match_opcode, 0},
{"th.vrgather.vx", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,sVm",
    MATCH_VRGATHERVX, MASK_VRGATHERVX, match_opcode, 0},
{"th.vrgather.vi", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,VjVm",
    MATCH_VRGATHERVI, MASK_VRGATHERVI, match_opcode, 0},
{"th.vcompress.vm", 0, INSN_CLASS_XTHEADVECTOR, "Vd,Vt,Vs",
    MATCH_VCOMPRESSVM, MASK_VCOMPRESSVM, match_opcode, 0},
{"th.vmaqa.vv", 0, INSN_CLASS_XTHEADVDOT, "Vd,Vs,VtVm", MATCH_TH_VMAQA_VV,
    MASK_TH_VMAQA_VV, match_opcode, 0},
{"th.vmaqau.vv", 0, INSN_CLASS_XTHEADVDOT, "Vd,Vs,VtVm", MATCH_TH_VMAQAU_VV,
    MASK_TH_VMAQAU_VV, match_opcode, 0},
{"th.vmaqasu.vv", 0, INSN_CLASS_XTHEADVDOT, "Vd,Vs,VtVm",
    MATCH_TH_VMAQASU_VV, MASK_TH_VMAQASU_VV, match_opcode, 0},
{"th.vmaqa.vx", 0, INSN_CLASS_XTHEADVDOT, "Vd,s,VtVm", MATCH_TH_VMAQA_VX,
    MASK_TH_VMAQA_VX, match_opcode, 0},
{"th.vmaqau.vx", 0, INSN_CLASS_XTHEADVDOT, "Vd,s,VtVm", MATCH_TH_VMAQAU_VX,
    MASK_TH_VMAQAU_VX, match_opcode, 0},
{"th.vmaqasu.vx", 0, INSN_CLASS_XTHEADVDOT, "Vd,s,VtVm",
    MATCH_TH_VMAQASU_VX, MASK_TH_VMAQASU_VX, match_opcode, 0},
{"th.vmaqaus.vx", 0, INSN_CLASS_XTHEADVDOT, "Vd,s,VtVm",
    MATCH_TH_VMAQAUS_VX, MASK_TH_VMAQAUS_VX, match_opcode, 0},"""

import re

def get_first_args(input_str):
    lines = input_str.strip().split("\n")
    names = []
    for line in lines:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        m = re.match(r'\{\s*"([^"]+)"', line)
        if m:
            names.append(f'"{m.group(1)}"')  # double quotes for C++
    return names

def validate_line_count(input_lines, first_args_list):
    """
    Checks that the number of non-empty input lines equals the number of first_args extracted.
    """
    input_count = len([line for line in input_lines.splitlines() if line.strip()])
    output_count = len(first_args_list)

    if input_count != output_count:
        raise ValueError(f"Line count mismatch: {input_count} input lines vs {output_count} extracted mnemonics")

    print("Line count validated successfully!")

    # Usage
first_args_list = get_first_args(input_lines)

cpp_vector = "std::vector<std::string> mnemonics = {\n    " + ",\n    ".join(first_args_list) + "\n};"
print(cpp_vector)
